## Usage

In [1]:
from IPython.display import display
import pandas as pd

### TSETMC Website API
Fetches all Bourse and FaraBours data (suitable for screening the total market).

In [31]:
from tseopt import get_all_options_data

entire_option_market_data = get_all_options_data()

display(entire_option_market_data.head(5))
print(entire_option_market_data.iloc[0])

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,24000,15,...,31432,1363,اختيارخ اهرم-24000-1404/01/27,ضهرم0120,2490,59,2588,50,256787,call
1,1704,778253364357513,وبملت,2345,2348,2280,20241221,20250416,2347,15,...,109180,464,اختيارخ وبملت-2347-1404/01/27,ضملت0120,66,300,80,2000,279122,call
2,1000,22312990497291517,سامان,1796,1790,1790,20250127,20250511,1500,40,...,17,2,اختيارخ سامان-1500-14040221,ضسامان200,350,2,400,38,125906,call
3,1389,46348559193224090,فولاد,4086,4100,3981,20241214,20250409,2160,8,...,2,1,اختيارخ فولاد-2160-1404/01/20,ضفلا0111,1901,20,0,0,100489,call
4,1000,48990026850202503,خگستر,4658,4678,4542,20250222,20250625,6000,85,...,0,0,اختيارخ خگستر-6000-1404/04/04,ضستر4020,1,100,0,0,0,call

contract_size                                        1000
ua_tse_code                             17914401175772326
ua_ticker                                            اهرم
ua_close_price                                      25330
ua_last_price                                       25470
ua_yesterday_price                                  24730
begin_date                                       20241123
end_date                                         20250416
strike_price                                        24000
days_to_maturity                                       15
tse_code                                32154096324950679
last_price                                           2550
open_positions                                     256787
close_price                                          2344
yesterday_price                                      1312
notional_value                             796172560000.0
trades_value                                73663019000.0
trades_volume                                       31432
trades_num                                           1363
name                        اختيارخ اهرم-24000-1404/01/27
ticker                                           ضهرم0120
bid_price                                            2490
bid_volume                                             59
ask_price                                            2588
ask_volume                                             50
yesterday_open_positions                           256787
option_type                                          call
Name: 0, dtype: object

### Screen Market

In [ ]:
from tseopt.use_case.screen_market import OptionMarket, convert_to_billion_toman

option_market = OptionMarket(entire_option_market_data=entire_option_market_data)

print(f"total_trade_value: {option_market.total_trade_value / 1e10:.0f} B Toman", end="\n\n")

most_trade_value_calls = pd.DataFrame(option_market.most_trade_value.get("call"))
most_trade_value_calls['ticker'] = most_trade_value_calls['ticker'].astype(str)
most_trade_value_calls["trades_value"] = convert_to_billion_toman(most_trade_value_calls["trades_value"])


most_trade_value_puts = pd.DataFrame(option_market.most_trade_value.get("put"))
most_trade_value_puts['ticker'] = most_trade_value_puts['ticker'].astype(str)
most_trade_value_puts["trades_value"] = convert_to_billion_toman(most_trade_value_puts["trades_value"])


most_trade_value_by_underlying_asset = pd.DataFrame(option_market.most_trade_value_by_underlying_asset)
most_trade_value_by_underlying_asset[["call", "put", "total"]] = convert_to_billion_toman(most_trade_value_by_underlying_asset[["call", "put", "total"]])


display(most_trade_value_calls)
display(most_trade_value_puts)
display(most_trade_value_by_underlying_asset)

total_trade_value: 236 B Toman

     ticker   trades_value
0  ضهرم2018  47.65 B Toman
1  ضهرم2016  19.79 B Toman
2  ضهرم0121  13.43 B Toman
3  ضهرم2017   10.6 B Toman
4  ضملت0118   7.98 B Toman

     ticker   trades_value
0  طهرم2016  16.49 B Toman
1  طهرم0120   2.56 B Toman
2  طهرم2017   2.36 B Toman
3  طهرم0121   2.06 B Toman
4  طستا0128   0.97 B Toman

  ua_ticker            call            put           total
0      اهرم  144.04 B Toman  25.54 B Toman  169.58 B Toman
1     وبملت   23.35 B Toman   0.03 B Toman   23.38 B Toman
2      شستا   19.27 B Toman   1.74 B Toman   21.01 B Toman
3       ذوب   10.12 B Toman   0.01 B Toman   10.13 B Toman
4    وبصادر    6.73 B Toman    0.0 B Toman    6.73 B Toman

### Options Chains

In [14]:
from tseopt.use_case.options_chains import Chains

chains = Chains(entire_option_market_data)

# Display underlying asset information to help select ua_tse_codes
print("Underlying Asset Information:")
print(chains.underlying_asset_info.head(5))

ua_tse_code = "17914401175772326" # اهرم

# Option types can be "call", "put", or "both"
options = chains.options(ua_tse_code=ua_tse_code, option_type="both")
date_chain = chains.make_date_chains(ua_tse_code=ua_tse_code, option_type="both") 
strike_price_chain = chains.make_strike_price_chains(ua_tse_code=ua_tse_code, option_type="call")
display(options)

# strike_price_chain and date_chain are generators.
# If you're not familiar with generators (and if you're wondering what the heck they are!), 
# uncomment the lines below to convert them to lists

# strike_price_chain = list(strike_price_chain)
# date_chain = list(date_chain)

Underlying Asset Information:
         ua_tse_code ua_ticker
0  17914401175772326      اهرم
1    778253364357513     وبملت
2   2400322364771558      شستا
3  71483646978964608       ذوب
4  28320293733348826    وبصادر

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,11000,15,...,20,7,اختيارخ اهرم-11000-1404/01/27,ضهرم0111,0,0,17200,2,1892,call
1,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,12000,15,...,1,1,اختيارخ اهرم-12000-1404/01/27,ضهرم0112,12000,5,14200,8,788,call
2,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,13000,15,...,0,0,اختيارخ اهرم-13000-1404/01/27,ضهرم0113,2,1000,0,0,777,call
3,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,14000,15,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,10000,5,12999,14,917,call
4,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,15000,15,...,0,0,اختيارخ اهرم-15000-1404/01/27,ضهرم0115,0,0,0,0,49,call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,1000,17914401175772326,اهرم,25330,25470,24730,20250315,20250820,28000,141,...,0,0,اختيارف اهرم-28000-1404/05/29,طهرم5020,1,100,0,0,0,put
952,1000,17914401175772326,اهرم,25330,25470,24730,20250315,20250820,30000,141,...,0,0,اختيارف اهرم-30000-1404/05/29,طهرم5021,1,100,0,0,0,put
953,1000,17914401175772326,اهرم,25330,25470,24730,20250315,20250820,34000,141,...,0,0,اختيارف اهرم-34000-1404/05/29,طهرم5022,1,100,0,0,0,put
954,1000,17914401175772326,اهرم,25330,25470,24730,20250315,20250820,38000,141,...,0,0,اختيارف اهرم-38000-1404/05/29,طهرم5023,1,100,0,0,0,put
955,1000,17914401175772326,اهرم,25330,25470,24730,20250315,20250820,42000,141,...,0,0,اختيارف اهرم-42000-1404/05/29,طهرم5024,1,100,0,0,0,put

In [25]:
date_chain = list(date_chain)
first_chain = date_chain[0]

name = first_chain.loc[0, "name"]
jalali_date = name.split("-")[2]
print("Date: ", jalali_date)
display(first_chain.head(10))

Date:  1404/01/27

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,11000,15,...,20,7,اختيارخ اهرم-11000-1404/01/27,ضهرم0111,0,0,17200,2,1892,call
1,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,11000,15,...,0,0,اختيارف اهرم-11000-1404/01/27,طهرم0111,0,0,0,0,0,put
2,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,12000,15,...,0,0,اختيارف اهرم-12000-1404/01/27,طهرم0112,0,0,0,0,0,put
3,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,12000,15,...,1,1,اختيارخ اهرم-12000-1404/01/27,ضهرم0112,12000,5,14200,8,788,call
4,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,13000,15,...,0,0,اختيارخ اهرم-13000-1404/01/27,ضهرم0113,2,1000,0,0,777,call
5,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,13000,15,...,0,0,اختيارف اهرم-13000-1404/01/27,طهرم0113,0,0,0,0,0,put
6,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,14000,15,...,0,0,اختيارف اهرم-14000-1404/01/27,طهرم0114,0,0,0,0,0,put
7,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,14000,15,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,10000,5,12999,14,917,call
8,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,15000,15,...,0,0,اختيارخ اهرم-15000-1404/01/27,ضهرم0115,0,0,0,0,49,call
9,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,15000,15,...,0,0,اختيارف اهرم-15000-1404/01/27,طهرم0115,0,0,0,0,0,put

In [26]:
for idx, chain in enumerate(strike_price_chain):
    print("Strike Price: ", chain.loc[0, "strike_price"])
    display(chain)
    print("\n\n")
    if idx > 2:
        print("and ...")
        break

Strike Price:  11000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,11000,15,...,20,7,اختيارخ اهرم-11000-1404/01/27,ضهرم0111,0,0,17200,2,1892,call

Strike Price:  12000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,12000,15,...,1,1,اختيارخ اهرم-12000-1404/01/27,ضهرم0112,12000,5,14200,8,788,call

Strike Price:  13000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,13000,15,...,0,0,اختيارخ اهرم-13000-1404/01/27,ضهرم0113,2,1000,0,0,777,call

Strike Price:  14000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,25330,25470,24730,20241123,20250416,14000,15,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,10000,5,12999,14,917,call

and ...

### Historical Order Book

In [27]:
from tseopt import fetch_historical_lob

jalali_date = "1403-10-24"
tse_code = "17091434834979599" # ضهرم1110

all_lob = fetch_historical_lob(tse_code=tse_code, jalali_date=jalali_date)
display(all_lob)

,level,ask_number,ask_volume,ask_price,bid_price,bid_volume,bid_number,time
0,1,0,0,0.0,3030.0,15,1,06:01:28
1,2,0,0,0.0,2750.0,20,1,06:01:28
2,3,0,0,0.0,2500.0,1,1,06:01:28
3,4,0,0,0.0,1.0,1,1,06:01:28
4,5,0,0,0.0,0.0,0,0,06:01:28
...,...,...,...,...,...,...,...,...
29062,1,1,1,3695.0,3625.0,61,2,12:29:59
29063,2,2,46,3696.0,3624.0,200,1,12:29:59
29064,3,1,200,3698.0,3623.0,3,1,12:29:59
29065,4,2,109,3699.0,3622.0,116,2,12:29:59
29066,5,4,254,3700.0,3621.0,9,3,12:29:59

In [28]:
from tseopt import take_lob_screenshot

specific_time = "10:50"
lob = take_lob_screenshot(entire_data=all_lob, specific_time=specific_time)
display(lob)

,level,ask_number,ask_volume,ask_price,bid_price,bid_volume,bid_number,time
0,1,1,70,3824.0,3820.0,400,2,10:49:59
1,2,1,1,3825.0,3803.0,12,1,10:49:59
2,3,1,10,3835.0,3802.0,121,1,10:49:59
3,4,7,133,3850.0,3801.0,292,3,10:49:59
4,5,1,5,3880.0,3782.0,8,1,10:49:59

### Tadbir API
Provides low latency and more detailed data (such as initial margin and order book). This may be suitable for obtaining data for actual trading.

In [29]:
from tseopt import tadbir_api

from pprint import pprint

isin_list = ["IRO9AHRM2501", "IROATVAF0621", "IRO9BMLT2771", "IRO9TAMN8991", "IRO9IKCO81M1"]

bulk_data = tadbir_api.get_last_bulk_data(isin_list=isin_list)
detail_data = tadbir_api.get_detail_data(isin_list[0])
symbol_info = detail_data.get("symbol_info")
order_book = pd.DataFrame(detail_data.get("order_book"))

display(bulk_data)

pprint(symbol_info)
display(order_book)

,BasisVolume,ClosingPrice,CompanyName,BestBuyPrice,BestBuyQuantity,BestSellPrice,BestSellQuantity,NoBestBuy,NoBestSell,FirstTradedPrice,...,TotalTradeValue,TradeDate,varSign,ClosingPriceVar,ClosingPriceVarPercent,LastTradedPriceVar,LastTradedPriceVarPercent,tse_code,SectorCodeId,cs
0,1.0,8194.0,اختیارخ اهرم-16000-1403/11/27,100.0,100,0.0,0,1,0,0.0,...,0.0,1403/11/27 12:29,1,0.0,0.0,0.0,0.0,18154069997422059,None,1000
1,1.0,9335.0,اختیارخ توان-16000-14031002,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/10/2 12:29,-1,0.0,0.0,0.0,0.0,14732757416991570,None,1000
2,1.0,1053.0,اختیارخ وبملت-1800-1403/11/27,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/11/27 12:24,-1,0.0,0.0,0.0,0.0,48841241645050970,None,1000
3,1.0,98.0,اختیارخ شستا-850-1403/08/09,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/8/9 12:29,0,0.0,0.0,0.0,0.0,18794200601794224,None,1000
4,1.0,1.0,اختیارخ خودرو-4000-1403/03/09,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/3/9 10:29,0,0.0,0.0,0.0,0.0,414085078149021,None,1000

{'BaseVolume': 1,
 'CP12': 0,
 'ClosingPrice': 8194.0,
 'CompanyTitle': 'اختیارخ اهرم-16000-1403/11/27',
 'GroupStateID': 8,
 'HighAllowedPrice': 500000.0,
 'HighPrice': 0,
 'InstrumentCode': '18154069997422059',
 'IsCautionAgreement': False,
 'IsSepahAgreement': False,
 'LastTradedPrice': 7997.0,
 'LotSize': 1,
 'LowAllowedPrice': 1.0,
 'LowPercent': 100,
 'LowPrice': 0,
 'MarketType': 'MarketType.BuyOption',
 'MaxPercent': 6002,
 'MaxQuantityOrder': 1000,
 'MinQuantityOrder': 1,
 'NSCCode': 'IRO9AHRM2501',
 'RefPrice': 8194.0,
 'Symbol': 'ضهرم1105',
 'SymbolStateId': 7,
 'TickSize': 1.0,
 'TotalNumberOfSharesTraded': 0,
 'TotalNumberOfTrades': 0,
 'TotalTradeValue': 0.0,
 'TradeDate': '1403/11/27 - 12:29:54',
 'UA_LastTradedPrice': 25470.0,
 'UA_isin': 'IRT1AHRM0001',
 'YesterdayPrice': 8194.0,
 'contractSize': 1000,
 'contractStartDate': '1403/07/01',
 'cpv': 0.0,
 'cpvp': 0.0,
 'crn': 'ریال',
 'crp': 1,
 'exerciseDate': '1403/11/27',
 'gc': '3A',
 'initial_margin': 5080000.0,
 'iso': True,
 'lpv': 0.0,
 'lpvp': 0.0,
 'mbop': 0,
 'mcaop': 112000,
 'mcop': 112000,
 'mmop': 2250000,
 'openPositionNum': 11391,
 'pv': 0.0,
 'rm': 13274000.0,
 'strikePrice': 16000.0,
 'th': 499997.0,
 'tl': 0.0,
 'vs': 1}

,BestBuyPrice,BestSellPrice,BestSellQuantity,BestBuyQuantity,NoBestBuy,NoBestSell,NSCCode,Place
0,100.0,0.0,0,100,1,0,IRO9AHRM2501,1

### Mercantile Exchange
Fetches all data which mercantile exchange website provides.

In [30]:
from tseopt import make_a_mercantile_data_object


md = make_a_mercantile_data_object()
md.update_data(timeout=20)
print(md.gavahi[0])
print(md.sandoq[0])
print(md.salaf[0])
print(md.cdc[0])
print(md.all_market)
print(md.future_date_time)
print(md.future[0])
print(md.markets_info[0])

{'ID': '66776904822812259', 'Code': 'IRK1A11504A7', 'Symbol': 'زعف0410پ09', 'Name': 'زعفران0410نگين نوين(پ)', 'YesterdayPrice': 0.0, 'FinalPrice': 0.0, 'LastPrice': 0.0, 'PriceChange': 0.0, 'FirstPrice': 0.0, 'MinPrice': 0.0, 'MaxPrice': 0.0, 'Quantity': 0, 'Volume': 0.0, 'Value': 0.0, 'DemandVolume1': 12, 'DemandQuantity1': 1, 'DemandPrice1': 1122222.0, 'OfferPrice1': 1139990.0, 'OfferQuantity1': 1, 'OfferVolume1': 500, 'DemandVolume2': 11, 'DemandQuantity2': 1, 'DemandPrice2': 1112222.0, 'OfferPrice2': 1139999.0, 'OfferQuantity2': 1, 'OfferVolume2': 446, 'DemandVolume3': 500, 'DemandQuantity3': 1, 'DemandPrice3': 1110007.0, 'OfferPrice3': 1140000.0, 'OfferQuantity3': 1, 'OfferVolume3': 1923, 'DemandVolume4': 100, 'DemandQuantity4': 1, 'DemandPrice4': 1110006.0, 'OfferPrice4': 1148000.0, 'OfferQuantity4': 1, 'OfferVolume4': 993, 'DemandVolume5': 0, 'DemandQuantity5': 0, 'DemandPrice5': 0.0, 'OfferPrice5': 1170000.0, 'OfferQuantity5': 2, 'OfferVolume5': 8000, 'Time': '0', 'Status': False, 'Buy_CountI': 0, 'Buy_CountN': 0, 'Buy_I_Volume': 0.0, 'Buy_N_Volume': 0.0, 'Sell_CountI': 0, 'Sell_CountN': 0, 'Sell_I_Volume': 0.0, 'Sell_N_Volume': 0.0, 'ModifyDate': '0001-01-01T00:00:00', 'ModifyTime': '08:36:20'}
{'ID': '30895446582685604', 'Code': 'IRTKEMRL0004', 'Symbol': 'امرالد', 'Name': 'صندوق س.پشتوانه طلاي كيميا', 'YesterdayPrice': 0.0, 'FinalPrice': 0.0, 'LastPrice': 0.0, 'PriceChange': 0.0, 'FirstPrice': 0.0, 'MinPrice': 0.0, 'MaxPrice': 0.0, 'Quantity': 0, 'Volume': 0.0, 'Value': 0.0, 'DemandVolume1': 12919, 'DemandQuantity1': 9, 'DemandPrice1': 10770.0, 'OfferPrice1': 10777.0, 'OfferQuantity1': 3, 'OfferVolume1': 200883, 'DemandVolume2': 1000, 'DemandQuantity2': 1, 'DemandPrice2': 10768.0, 'OfferPrice2': 10790.0, 'OfferQuantity2': 1, 'OfferVolume2': 100000, 'DemandVolume3': 29000, 'DemandQuantity3': 4, 'DemandPrice3': 10766.0, 'OfferPrice3': 10799.0, 'OfferQuantity3': 1, 'OfferVolume3': 10000, 'DemandVolume4': 165100, 'DemandQuantity4': 4, 'DemandPrice4': 10765.0, 'OfferPrice4': 10800.0, 'OfferQuantity4': 4, 'OfferVolume4': 97291, 'DemandVolume5': 94, 'DemandQuantity5': 1, 'DemandPrice5': 10763.0, 'OfferPrice5': 10801.0, 'OfferQuantity5': 1, 'OfferVolume5': 20000, 'Time': '0', 'Status': False, 'Buy_CountI': 0, 'Buy_CountN': 0, 'Buy_I_Volume': 0.0, 'Buy_N_Volume': 0.0, 'Sell_CountI': 0, 'Sell_CountN': 0, 'Sell_I_Volume': 0.0, 'Sell_N_Volume': 0.0, 'ModifyDate': '0001-01-01T00:00:00', 'ModifyTime': '08:36:20'}
{'ID': '67574040984805133', 'Code': 'IRBKZARN0563', 'Symbol': 'عزرند', 'Name': 'سلف فيلم شفاف لفاف صنعت زرند', 'YesterdayPrice': 0.0, 'FinalPrice': 0.0, 'LastPrice': 0.0, 'PriceChange': 0.0, 'FirstPrice': 0.0, 'MinPrice': 0.0, 'MaxPrice': 0.0, 'Quantity': 0, 'Volume': 0.0, 'Value': 0.0, 'DemandVolume1': 5000, 'DemandQuantity1': 1, 'DemandPrice1': 1238500.0, 'OfferPrice1': 0.0, 'OfferQuantity1': 0, 'OfferVolume1': 0, 'DemandVolume2': 0, 'DemandQuantity2': 0, 'DemandPrice2': 0.0, 'OfferPrice2': 0.0, 'OfferQuantity2': 0, 'OfferVolume2': 0, 'DemandVolume3': 0, 'DemandQuantity3': 0, 'DemandPrice3': 0.0, 'OfferPrice3': 0.0, 'OfferQuantity3': 0, 'OfferVolume3': 0, 'DemandVolume4': 0, 'DemandQuantity4': 0, 'DemandPrice4': 0.0, 'OfferPrice4': 0.0, 'OfferQuantity4': 0, 'OfferVolume4': 0, 'DemandVolume5': 0, 'DemandQuantity5': 0, 'DemandPrice5': 0.0, 'OfferPrice5': 0.0, 'OfferQuantity5': 0, 'OfferVolume5': 0, 'Time': '0', 'Status': False, 'Buy_CountI': 0, 'Buy_CountN': 0, 'Buy_I_Volume': 0.0, 'Buy_N_Volume': 0.0, 'Sell_CountI': 0, 'Sell_CountN': 0, 'Sell_I_Volume': 0.0, 'Sell_N_Volume': 0.0, 'ModifyDate': '0001-01-01T00:00:00', 'ModifyTime': '08:36:20'}
{'ContractID': 43, 'ContractCode': 'CD1SIB0001', 'ContractDescription': 'گواهی سپرده پیوسته شمش نقره 999.9', 'LastTradingPersianDate': '1410/12/01', 'ContractSize': 1.0, 'ContractSizeUnitFaDesc': 'ضریب تبدیل نماد به گروه انبار', 'TotalAssetChangesColor': 'Gray', 'ContractCurrencyFaDesc': 'ریال', 'LastSettlementPrice': 1230900.0, 'AskPrice1': 0.0, 'AskVolume1': 0, 'AskPrice2': 0.0, 'AskVolume2': 0, 'AskPrice3': 0.0, 'AskVolume3': 0, 'AskTotalVolume': 0, 'BidPrice1': 0.0, 'BidVolume1': 0, 'BidPrice2': 0.0, 'BidVolume2': 0, 'BidPrice3': 0.0, 'BidVolume3': 0, 'BidTotalVolume': 0, 'ContractCurrencyEnDesc': 'Rials', 'LastSettlementPricePersianDate': '1404/01/11', 'LastUpdate': '2025-04-01T08:30:01.32', 'HighTradedPriceChanges': 0.0, 'HighTradedPrice': 0.0, 'LastTradedPriceChangesColor': 'Gray', 'LastTradedPriceChangesVisibility': 'Collapsed', 'LastTradedPriceChangesPercent': 0.0, 'LastTradedPriceChanges': 0.0, 'LastTradedPriceTime': '', 'LastTradedPrice': 0.0, 'FirstTradedPriceChangesColor': 'Gray', 'FirstTradedPriceChangesVisibility': 'Collapsed', 'FirstTradedPriceChangesPercent': 0.0, 'FirstTradedPriceChanges': 0.0, 'FirstTradedPriceTime': '', 'FirstTradedPrice': 0.0, 'HighTradedPriceChangesPercent': 0.0, 'HighTradedPriceChangesVisibility': 'Collapsed', 'HighTradedPriceChangesColor': 'Gray', 'LowTradedPrice': 0.0, 'TotalAssetChangesVisibility': 'Visible', 'TotalAssetChangesPercent': 0.0, 'TotalAssetChanges': 12064000, 'TotalAsset': 12064000, 'TradesValueCurrencyEnDesc': '', 'TradesValueCurrencyFaDesc': '', 'OrderTimeVisibility': 'Collapsed', 'TradesValue': 0.0, 'TradesVolume': 0, 'TradesCount': 0, 'LowTradedPriceChangesColor': 'Gray', 'LowTradedPriceChangesVisibility': 'Collapsed', 'LowTradedPriceChangesPercent': 0.0, 'LowTradedPriceChanges': 0.0, 'TradesVolumeVisibility': 'Collapsed', 'OrdersPersianDateTime': '', 'OrdersDateTime': None, 'OrdersCounter': -1, 'CommodityID': 21, 'CommodityName': 'شمش نقره', 'CommodityColor': '#F0F0F0 ', 'CommodityColor1': '#E3E3E3 ', 'TradesCounter': -1, 'IsOrdersHighLight': False, 'IsTradesHighLight': False}
{'id': 1, 'Description': 'تابلو آتی', 'TradeCount': 0, 'Buyers': 0, 'Sellers': 0, 'LegalBuyerCount': 0, 'NaturalBuyerCount': 0, 'LegalSellerCount': 0, 'NaturalSellerCount': 0}
None
{'ContractID': 284, 'LastTradingDate': '2025-04-15T00:00:00', 'ContractCode': 'ETCFA04', 'ContractDescription': 'قرارداد آتی صندوق طلای لوتوس تحویل فروردین ماه 1404', 'ContractSize': 1000.0, 'ContractSizeUnitFaDesc': 'واحد', 'ContractSizeUnitEnDesc': '-', 'ContractCurrencyFaDesc': 'ریال', 'ContractCurrencyEnDesc': 'Rials', 'ContractCurrencyDecimalPlaces': None, 'LastSettlementPrice': 638490.0, 'LastSettlementPriceDate': '2025-03-31T00:00:00', 'YesterdayOpenInterests': None, 'BidTotalVolume': 0, 'BidVolume1': 0, 'BidPrice1': 0.0, 'BidVolume2': 0, 'BidPrice2': 0.0, 'BidVolume3': 0, 'BidPrice3': 0.0, 'BidVolume4': 0, 'BidPrice4': 0.0, 'BidVolume5': 0, 'BidPrice5': 0.0, 'AskTotalVolume': 0, 'AskVolume1': 0, 'AskPrice1': 0.0, 'AskVolume2': 0, 'AskPrice2': 0.0, 'AskVolume3': 0, 'AskPrice3': 0.0, 'AskVolume4': 0, 'AskPrice4': 0.0, 'AskVolume5': 0, 'AskPrice5': 0.0, 'OrdersDateTime': None, 'FirstTradedPrice': 0.0, 'FirstTradedPriceTime': '', 'FirstTradedPriceChanges': 0.0, 'FirstTradedPriceChangesPercent': 0.0, 'LastTradedPrice': 0.0, 'LastTradedPriceTime': '', 'LastTradedPriceChanges': 0.0, 'LastTradedPriceChangesPercent': 0.0, 'HighTradedPrice': 0.0, 'HighTradedPriceChanges': 0.0, 'HighTradedPriceChangesPercent': 0.0, 'LowTradedPrice': 0.0, 'LowTradedPriceChanges': 0.0, 'LowTradedPriceChangesPercent': 0.0, 'AverageTradedPrice': None, 'OpeningPrice': None, 'ClosingPrice': None, 'TradesCount': 0, 'TradesVolume': 0, 'TradesValue': 0.0, 'TradesValueCurrencyFaDesc': '', 'TradesValueCurrencyEnDesc': '', 'OpenInterests': 1216, 'OpenInterestsChanges': 0, 'OpenInterestsChangesPercent': 0.0, 'InitialMargin': 110000000.0, 'MaintenanceMargin': 77000000.0, 'LastUpdate': '2025-04-01T01:00:01.15', 'Expired': False, 'LegalBuyerCount': 0, 'LegalSellerCount': 0, 'NaturalBuyerCount': 0, 'NaturalSellerCount': 0, 'TodayLiveSettlement': 0.0, 'TradeCount': 0, 'TradeVolume': 0, 'PersianOrdersDateTime': None, 'PersianLastSettlementPriceDate': None, 'PesrsianLastTradingDate': None}
{'_StrikeLevel': -2, '_StrikePrice': 8100000.0, '_LastUpdate': '2025-04-01T01:00:00.78', '_PutContractVisibility': 'Visible', '_ContractCategory': 'OR04\t\t\tتاریخ سررسید: 1404/02/21', '_CommodityGroup': 'CDC', '_ContractSubGroup': 'CDCOR04', '_CallContractID': 1001534, '_CallContractCode': 'GBOR04C810', '_CallContractDescription': 'قرارداد اختیار معامله خرید شمش طلا سررسید اردیبهشت ماه 1404 با قیمت اعمال 8،100،000 ریال', '_CallLastTradingPersianDate': '1404/02/21', '_CallContractSize': 1.0, '_CallContractSizeUnitFaDesc': 'CD1GOB0001', '_CallContractCurrencyFaDesc': 'ریال', '_CallContractCurrencyEnDesc': 'Rials', '_CallLastSettlementPrice': 3283450.0, '_CallLastSettlementPricePersianDate': '1404/01/10', '_CallBidTotalVolume': None, '_CallBidVolume1': None, '_CallBidPrice1': None, '_CallBidVolume2': None, '_CallBidPrice2': None, '_CallBidVolume3': None, '_CallBidPrice3': None, '_CallBidVolume4': 0, '_CallBidPrice4': 0.0, '_CallBidVolume5': 0, '_CallBidPrice5': 0.0, '_CallAskTotalVolume': None, '_CallAskVolume1': None, '_CallAskPrice1': None, '_CallAskVolume2': None, '_CallAskPrice2': None, '_CallAskVolume3': None, '_CallAskPrice3': None, '_CallAskVolume4': 0, '_CallAskPrice4': 0.0, '_CallAskVolume5': 0, '_CallAskPrice5': 0.0, '_CallOrdersDateTime': None, '_CallOrdersPersianDateTime': '', '_CallOrderTimeVisibility': 'Collapsed', '_CallFirstTradedPrice': None, '_CallFirstTradedPriceTime': '', '_CallFirstTradedPriceChanges': None, '_CallFirstTradedPriceChangesPercent': None, '_CallFirstTradedPriceChangesVisibility': 'Collapsed', '_CallFirstTradedPriceChangesColor': 'Gray', '_CallLastTradedPrice': None, '_CallLastTradedPriceTime': '', '_CallLastTradedPriceChanges': None, '_CallLastTradedPriceChangesPercent': None, '_CallLastTradedPriceChangesVisibility': 'Collapsed', '_CallLastTradedPriceChangesColor': 'Gray', '_CallHighTradedPrice': None, '_CallHighTradedPriceChanges': None, '_CallHighTradedPriceChangesPercent': None, '_CallHighTradedPriceChangesVisibility': 'Collapsed', '_CallHighTradedPriceChangesColor': 'Gray', '_CallInitialMargin': 2220000.0, '_CallRequiredMargin': 5495993.0, '_CallLowTradedPrice': None, '_CallLowTradedPriceChanges': None, '_CallLowTradedPriceChangesPercent': None, '_CallLowTradedPriceChangesVisibility': 'Collapsed', '_CallLowTradedPriceChangesColor': 'Gray', '_CallTradesCount': 0, '_CallTradesVolume': None, '_CallTradesVolumeVisibility': 'Collapsed', '_CallTradesValue': None, '_CallTradesValueCurrencyFaDesc': '', '_CallTradesValueCurrencyEnDesc': '', '_CallOpenInterests': None, '_CallOpenInterestsChanges': None, '_CallOpenInterestsChangesPercent': 0.0, '_CallOpenInterestsChangesVisibility': 'Collapsed', '_CallOpenInterestsChangesColor': 'Gray', '_PutContractID': 1001535, '_PutContractCode': 'GBOR04P810', '_PutContractDescription': 'قرارداد اختیار معامله فروش شمش طلا سررسید اردیبهشت ماه 1404 با قیمت اعمال 8،100،000 ریال', '_PutLastTradingPersianDate': '1404/02/21', '_PutContractSize': 1.0, '_PutContractSizeUnitFaDesc': 'CD1GOB0001', '_PutContractCurrencyFaDesc': 'ریال', '_PutContractCurrencyEnDesc': 'Rials', '_PutLastSettlementPrice': 106.0, '_PutLastSettlementPricePersianDate': '1404/01/10', '_PutBidTotalVolume': None, '_PutBidVolume1': None, '_PutBidPrice1': None, '_PutBidVolume2': None, '_PutBidPrice2': None, '_PutBidVolume3': None, '_PutBidPrice3': None, '_PutBidVolume4': 0, '_PutBidPrice4': 0.0, '_PutBidVolume5': 0, '_PutBidPrice5': 0.0, '_PutAskTotalVolume': None, '_PutAskVolume1': None, '_PutAskPrice1': None, '_PutAskVolume2': None, '_PutAskPrice2': None, '_PutAskVolume3': None, '_PutAskPrice3': None, '_PutAskVolume4': 0, '_PutAskPrice4': 0.0, '_PutAskVolume5': 0, '_PutAskPrice5': 0.0, '_PutOrdersDateTime': None, '_PutOrdersPersianDateTime': '', '_PutOrderTimeVisibility': 'Collapsed', '_PutFirstTradedPrice': None, '_PutFirstTradedPriceTime': '', '_PutFirstTradedPriceChanges': None, '_PutFirstTradedPriceChangesPercent': None, '_PutFirstTradedPriceChangesVisibility': 'Collapsed', '_PutFirstTradedPriceChangesColor': 'Gray', '_PutLastTradedPrice': None, '_PutLastTradedPriceTime': '', '_PutLastTradedPriceChanges': None, '_PutLastTradedPriceChangesPercent': None, '_PutLastTradedPriceChangesVisibility': 'Collapsed', '_PutLastTradedPriceChangesColor': 'Gray', '_PutHighTradedPrice': None, '_PutHighTradedPriceChanges': None, '_PutHighTradedPriceChangesPercent': None, '_PutHighTradedPriceChangesVisibility': 'Collapsed', '_PutHighTradedPriceChangesColor': 'Gray', '_PutInitialMargin': 820000.0, '_PutRequiredMargin': 820000.0, '_PutLowTradedPrice': None, '_PutLowTradedPriceChanges': None, '_PutLowTradedPriceChangesPercent': None, '_PutLowTradedPriceChangesVisibility': 'Collapsed', '_PutLowTradedPriceChangesColor': 'Gray', '_PutTradesCount': 0, '_PutTradesVolume': None, '_PutTradesVolumeVisibility': 'Collapsed', '_PutTradesValue': None, '_PutTradesValueCurrencyFaDesc': '', '_PutTradesValueCurrencyEnDesc': '', '_PutOpenInterests': None, '_PutOpenInterestsChanges': None, '_PutOpenInterestsChangesPercent': 0.0, '_PutOpenInterestsChangesVisibility': 'Collapsed', '_PutOpenInterestsChangesColor': 'Gray', 'StrikeLevel': -2, 'StrikePrice': 8100000.0, 'LastUpdate': '2025-04-01T01:00:00.78', 'PutContractVisibility': 'Visible', 'ContractCategory': 'OR04\t\t\tتاریخ سررسید: 1404/02/21', 'CommodityGroup': 'CDC', 'ContractSubGroup': 'CDCOR04', 'CallOrdersCounter': 0, 'CallTradesCounter': 0, 'CallIsOrdersHighLight': False, 'CallIsTradesHighLight': False, 'CallContractID': 1001534, 'CallContractCode': 'GBOR04C810', 'CallContractDescription': 'قرارداد اختیار معامله خرید شمش طلا سررسید اردیبهشت ماه 1404 با قیمت اعمال 8،100،000 ریال', 'CallLastTradingPersianDate': '1404/02/21', 'CallContractSize': 1.0, 'CallContractSizeUnitFaDesc': 'CD1GOB0001', 'CallContractCurrencyFaDesc': 'ریال', 'CallContractCurrencyEnDesc': 'Rials', 'CallLastSettlementPrice': 3283450.0, 'CallLastSettlementPricePersianDate': '1404/01/10', 'CallBidTotalVolume': None, 'CallBidVolume1': None, 'CallBidPrice1': None, 'CallBidVolume2': None, 'CallBidPrice2': None, 'CallBidVolume3': None, 'CallBidPrice3': None, 'CallBidVolume4': 0, 'CallBidPrice4': 0.0, 'CallBidVolume5': 0, 'CallBidPrice5': 0.0, 'CallAskTotalVolume': None, 'CallAskVolume1': None, 'CallAskPrice1': None, 'CallAskVolume2': None, 'CallAskPrice2': None, 'CallAskVolume3': None, 'CallAskPrice3': None, 'CallAskVolume4': 0, 'CallAskPrice4': 0.0, 'CallAskVolume5': 0, 'CallAskPrice5': 0.0, 'CallOrdersDateTime': None, 'CallOrdersPersianDateTime': '', 'CallOrderTimeVisibility': 'Collapsed', 'CallFirstTradedPrice': None, 'CallFirstTradedPriceTime': '', 'CallFirstTradedPriceChanges': None, 'CallFirstTradedPriceChangesPercent': None, 'CallFirstTradedPriceChangesVisibility': 'Collapsed', 'CallFirstTradedPriceChangesColor': 'Gray', 'CallLastTradedPrice': None, 'CallLastTradedPriceTime': '', 'CallLastTradedPriceChanges': None, 'CallLastTradedPriceChangesPercent': None, 'CallLastTradedPriceChangesVisibility': 'Collapsed', 'CallLastTradedPriceChangesColor': 'Gray', 'CallHighTradedPrice': None, 'CallHighTradedPriceChanges': None, 'CallHighTradedPriceChangesPercent': None, 'CallHighTradedPriceChangesVisibility': 'Collapsed', 'CallHighTradedPriceChangesColor': 'Gray', 'CallInitialMargin': 2220000.0, 'CallRequiredMargin': 5495993.0, 'CallLowTradedPrice': None, 'CallLowTradedPriceChanges': None, 'CallLowTradedPriceChangesPercent': None, 'CallLowTradedPriceChangesVisibility': 'Collapsed', 'CallLowTradedPriceChangesColor': 'Gray', 'CallTradesCount': 0, 'CallTradesVolume': None, 'CallTradesVolumeVisibility': 'Collapsed', 'CallTradesValue': None, 'CallTradesValueCurrencyFaDesc': '', 'CallTradesValueCurrencyEnDesc': '', 'CallOpenInterests': None, 'CallOpenInterestsChanges': None, 'CallOpenInterestsChangesPercent': 0.0, 'CallOpenInterestsChangesVisibility': 'Collapsed', 'CallOpenInterestsChangesColor': 'Gray', 'PutOrdersCounter': None, 'PutTradesCounter': None, 'PutIsOrdersHighLight': None, 'PutIsTradesHighLight': None, 'PutContractID': 1001535, 'PutContractCode': 'GBOR04P810', 'PutContractDescription': 'قرارداد اختیار معامله فروش شمش طلا سررسید اردیبهشت ماه 1404 با قیمت اعمال 8،100،000 ریال', 'PutLastTradingPersianDate': '1404/02/21', 'PutContractSize': 1.0, 'PutContractSizeUnitFaDesc': 'CD1GOB0001', 'PutContractCurrencyFaDesc': 'ریال', 'PutContractCurrencyEnDesc': 'Rials', 'PutLastSettlementPrice': 106.0, 'PutLastSettlementPricePersianDate': '1404/01/10', 'PutBidTotalVolume': None, 'PutBidVolume1': None, 'PutBidPrice1': None, 'PutBidVolume2': None, 'PutBidPrice2': None, 'PutBidVolume3': None, 'PutBidPrice3': None, 'PutBidVolume4': 0, 'PutBidPrice4': 0.0, 'PutBidVolume5': 0, 'PutBidPrice5': 0.0, 'PutAskTotalVolume': None, 'PutAskVolume1': None, 'PutAskPrice1': None, 'PutAskVolume2': None, 'PutAskPrice2': None, 'PutAskVolume3': None, 'PutAskPrice3': None, 'PutAskVolume4': 0, 'PutAskPrice4': 0.0, 'PutAskVolume5': 0, 'PutAskPrice5': 0.0, 'PutOrdersDateTime': None, 'PutOrdersPersianDateTime': '', 'PutOrderTimeVisibility': 'Collapsed', 'PutFirstTradedPrice': None, 'PutFirstTradedPriceTime': '', 'PutFirstTradedPriceChanges': None, 'PutFirstTradedPriceChangesPercent': None, 'PutFirstTradedPriceChangesVisibility': 'Collapsed', 'PutFirstTradedPriceChangesColor': 'Gray', 'PutLastTradedPrice': None, 'PutLastTradedPriceTime': '', 'PutLastTradedPriceChanges': None, 'PutLastTradedPriceChangesPercent': None, 'PutLastTradedPriceChangesVisibility': 'Collapsed', 'PutLastTradedPriceChangesColor': 'Gray', 'PutHighTradedPrice': None, 'PutHighTradedPriceChanges': None, 'PutHighTradedPriceChangesPercent': None, 'PutHighTradedPriceChangesVisibility': 'Collapsed', 'PutHighTradedPriceChangesColor': 'Gray', 'PutInitialMargin': 820000.0, 'PutRequiredMargin': 820000.0, 'PutLowTradedPrice': None, 'PutLowTradedPriceChanges': None, 'PutLowTradedPriceChangesPercent': None, 'PutLowTradedPriceChangesVisibility': 'Collapsed', 'PutLowTradedPriceChangesColor': 'Gray', 'PutTradesCount': 0, 'PutTradesVolume': None, 'PutTradesVolumeVisibility': 'Collapsed', 'PutTradesValue': None, 'PutTradesValueCurrencyFaDesc': '', 'PutTradesValueCurrencyEnDesc': '', 'PutOpenInterests': None, 'PutOpenInterestsChanges': None, 'PutOpenInterestsChangesPercent': 0.0, 'PutOpenInterestsChangesVisibility': 'Collapsed', 'PutOpenInterestsChangesColor': 'Gray'}

#### Gavahi

In [17]:
display(pd.DataFrame(md.gavahi).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,65409376773204752,IRK2GLAS0913,شيشه91ن,گواهي شيشه فلوت6بيرنگBكاويان,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
1,62478783041763871,IRK2N0390008,سي تيپ2ن37,گواهي سيمان تيپ2شمال(ن),0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
2,62180931969029505,IRK1K01604B3,سكه0411پ05,تمام سكه طرح جديد0411 آينده,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
3,56219836927718202,IRK2GLAS0749,شيشه74ن,گواهي شيشه فلوت4بيرنگAكاويان,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
4,48727383410956465,IRK2GLAS0210,شيشه21ن,گواهي شيشه فلوت4بيرنگAآسا,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25

#### Sandoq

In [18]:
display(pd.DataFrame(md.sandoq).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,51200575796028449,IRTKSAHR0008,سحرخيز,صندوق س. گروه زعفران سحرخيز,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
1,38544104313215500,IRTKJAVA0000,جواهر,صندوق س.پشتوانه طلا دناي زاگرس,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
2,33254899395816171,IRTKZARF0001,زر,صندوق س.پشتوانه طلاي زرافشان,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
3,28255729477187163,IRTKZARV0001,زروان,صندوق س.پشتوانه طلاي ويستا,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
4,6362118829011821,IRTKLIAN0008,ليان,صندوق س.پشتوانه طلاي ليان,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25

#### Salaf

In [19]:
display(pd.DataFrame(md.salaf).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,63624670675689374,IRBKSNG304A0,عسنگ3,سلف استاندارد سنگ آهن مركزي,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
1,51040923156442869,IRBKAPAK0542,عپاكشو,سلف موازي گروه صنعتي پاكشو,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
2,1185549032856396,IRBKABAH03B0,عبهمن,سلف خودرووانت كارا تك كابين,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
3,40246708135920665,IRBKSNG404A8,عسنگ4,سلف موازي سنگ آهن,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
4,39587043114049835,IRBKKAL30455,عكاله3,سلف شير فرادما كاله,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25

#### Future

In [20]:
display(pd.DataFrame(md.future).head(5))

,ContractID,LastTradingDate,ContractCode,ContractDescription,ContractSize,ContractSizeUnitFaDesc,ContractSizeUnitEnDesc,ContractCurrencyFaDesc,ContractCurrencyEnDesc,ContractCurrencyDecimalPlaces,...,LegalBuyerCount,LegalSellerCount,NaturalBuyerCount,NaturalSellerCount,TodayLiveSettlement,TradeCount,TradeVolume,PersianOrdersDateTime,PersianLastSettlementPriceDate,PesrsianLastTradingDate
0,284,2025-04-15T00:00:00,ETCFA04,قرارداد آتی صندوق طلای لوتوس تحویل فروردین ماه...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
1,285,2025-03-02T00:00:00,KBES03,قرارداد آتی صندوق طلای کهربا تحویل اسفند ماه 1...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
2,289,2025-02-17T00:00:00,GB29BA03,قرارداد آتی شمش طلای خام 995 تحویل بهمن ماه 1403,1.0,گرم,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
3,290,2025-06-17T00:00:00,KBKH04,قرارداد آتی صندوق طلای کهربا تحویل خرداد ماه 1...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
4,291,2025-07-15T00:00:00,ETCTR04,قرارداد آتی صندوق طلای لوتوس تحویل تیر ماه 1404,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None

#### CDC

In [21]:
display(pd.DataFrame(md.cdc).head(5))

,ContractID,ContractCode,ContractDescription,LastTradingPersianDate,ContractSize,ContractSizeUnitFaDesc,TotalAssetChangesColor,ContractCurrencyFaDesc,LastSettlementPrice,AskPrice1,...,OrdersPersianDateTime,OrdersDateTime,OrdersCounter,CommodityID,CommodityName,CommodityColor,CommodityColor1,TradesCounter,IsOrdersHighLight,IsTradesHighLight
0,43,CD1SIB0001,گواهی سپرده پیوسته شمش نقره 999.9,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Gray,ریال,964151.0,0.0,...,,None,-1,21,شمش نقره,#F0F0F0,#E3E3E3,-1,False,False
1,42,CD1GOC0001,گواهی سپرده پیوسته تمام سکه بهار آزادی طرح جدید,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Gray,ریال,565044118.0,0.0,...,,None,-1,4,سکه طلا,#64ffffce,#ffefef15,-1,False,False
2,41,CD1GOB0001,گواهی سپرده پیوسته شمش طلای +995,1410/12/01,10.0,ضریب تبدیل نماد به گروه انبار,Gray,ریال,7067104.0,0.0,...,,None,-1,2,شمش طلا,#fdf5e6,#fdf5e6,-1,False,False

#### markets_info

In [22]:
display(pd.DataFrame(md.markets_info).head(5))

,_StrikeLevel,_StrikePrice,_LastUpdate,_PutContractVisibility,_ContractCategory,_CommodityGroup,_ContractSubGroup,_CallContractID,_CallContractCode,_CallContractDescription,...,PutTradesVolume,PutTradesVolumeVisibility,PutTradesValue,PutTradesValueCurrencyFaDesc,PutTradesValueCurrencyEnDesc,PutOpenInterests,PutOpenInterestsChanges,PutOpenInterestsChangesPercent,PutOpenInterestsChangesVisibility,PutOpenInterestsChangesColor
0,-1,4600000.0,2025-01-14T17:00:02.873,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001150,GBBA03C460,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,None,Collapsed,None,,,NaN,NaN,0.0,Collapsed,Gray
1,0,4800000.0,2025-01-14T17:00:02.873,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001152,GBBA03C480,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,None,Collapsed,None,,,NaN,NaN,0.0,Collapsed,Gray
2,1,5000000.0,2025-01-14T17:00:02.877,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001154,GBBA03C500,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,None,Collapsed,None,,,NaN,NaN,0.0,Collapsed,Gray
3,2,5200000.0,2025-01-14T17:00:02.877,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001157,GBBA03C520,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,None,Collapsed,None,,,NaN,NaN,0.0,Collapsed,Gray
4,3,5400000.0,2025-01-14T17:00:02.887,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001194,GBBA03C540,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,None,Collapsed,None,,,NaN,NaN,0.0,Collapsed,Gray