## Usage

In [20]:
from IPython.display import display
import pandas as pd

### TSETMC Website API
Fetches all Bourse and FaraBours data (suitable for screening the total market).

In [21]:
from tseopt import get_all_options_data

entire_option_market_data = get_all_options_data()

display(entire_option_market_data.head(5))
print(entire_option_market_data.iloc[0])

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,11000,47,...,0,0,اختيارخ اهرم-11000-1403/11/24,ضهرم1100,12701,1,19620,1,16844,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,14000,110,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,8073,8,0,0,6,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,24000,110,...,0,0,اختيارخ اهرم-24000-1404/01/27,ضهرم0120,6400,20,11999,4,51,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,26000,110,...,0,0,اختيارخ اهرم-26000-1404/01/27,ضهرم0121,1870,1,0,0,2,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,24000,145,...,0,0,اختيارخ اهرم-24000-1404/02/31,ضهرم2016,1000,20,0,0,0,call

contract_size                                        1000
ua_tse_code                             17914401175772326
ua_ticker                                            اهرم
ua_close_price                                      28270
ua_last_price                                       28010
ua_yesterday_price                                  28470
begin_date                                       20240922
end_date                                         20250212
strike_price                                        11000
days_to_maturity                                       47
tse_code                                70188540003947248
last_price                                          17900
open_positions                                      16844
close_price                                         17900
yesterday_price                                     17900
notional_value                                        0.0
trades_value                                          0.0
trades_volume                                           0
trades_num                                              0
name                        اختيارخ اهرم-11000-1403/11/24
ticker                                           ضهرم1100
bid_price                                           12701
bid_volume                                              1
ask_price                                           19620
ask_volume                                              1
yesterday_open_positions                            16844
option_type                                          call
Name: 0, dtype: object

### Screen Market

In [10]:
from tseopt.use_case.screen_market import OptionMarket, convert_to_billion_toman

option_market = OptionMarket(entire_option_market_data=entire_option_market_data)

print(f"total_trade_value: {option_market.total_trade_value / 1e10:.0f} B Toman", end="\n\n")

most_trade_value_calls = pd.DataFrame(option_market.most_trade_value.get("call"))
most_trade_value_calls['ticker'] = most_trade_value_calls['ticker'].astype(str)
most_trade_value_calls["trades_value"] = convert_to_billion_toman(most_trade_value_calls["trades_value"])


most_trade_value_puts = pd.DataFrame(option_market.most_trade_value.get("put"))
most_trade_value_puts['ticker'] = most_trade_value_puts['ticker'].astype(str)
most_trade_value_puts["trades_value"] = convert_to_billion_toman(most_trade_value_puts["trades_value"])


most_trade_value_by_underlying_asset = pd.DataFrame(option_market.most_trade_value_by_underlying_asset)
most_trade_value_by_underlying_asset[["call", "put", "total"]] =convert_to_billion_toman(most_trade_value_by_underlying_asset[["call", "put", "total"]])


display(most_trade_value_calls)
display(most_trade_value_puts)
display(most_trade_value_by_underlying_asset)

total_trade_value: 511 B Toman

     ticker   trades_value
0  ضخود1136  121.7 B Toman
1  ضهرم1110  38.33 B Toman
2  ضخود1137  27.49 B Toman
3  ضخود1138  16.96 B Toman
4  ضستا1038  14.08 B Toman

     ticker   trades_value
0  طخود1137  22.17 B Toman
1  طهرم1110  11.55 B Toman
2  طخود1138   4.85 B Toman
3  طستا1040    1.8 B Toman
4  طخود1135   1.02 B Toman

  ua_ticker            call            put           total
0     خودرو  194.02 B Toman  28.98 B Toman   223.0 B Toman
1      اهرم  100.44 B Toman  15.42 B Toman  115.86 B Toman
2      شستا  101.09 B Toman   2.79 B Toman  103.87 B Toman
3       ذوب   19.99 B Toman   0.07 B Toman   20.06 B Toman
4      شپنا    7.44 B Toman    0.0 B Toman    7.44 B Toman

### Options Chains

In [27]:
from tseopt.use_case.options_chains import Chains

chains = Chains(entire_option_market_data)

# Display underlying asset information to help select ua_tse_codes
print("Underlying Asset Information:")
print(chains.underlying_asset_info.head(5))

ua_tse_code = "17914401175772326" # اهرم

# Option types can be "call", "put", or "both"
options = chains.options(ua_tse_code=ua_tse_code, option_type="both")
date_chain = chains.make_date_chains(ua_tse_code=ua_tse_code, option_type="both") 
strike_price_chain = chains.make_strike_price_chains(ua_tse_code=ua_tse_code, option_type="call")
display(options)

# strike_price_chain and date_chain are generators.
# If you're not familiar with generators (and if you're wondering what the heck they are!), 
# uncomment the lines below to convert them to lists

# strike_price_chain = list(strike_price_chain)
# date_chain = list(date_chain)

Underlying Asset Information:
         ua_tse_code ua_ticker
0  65883838195688438     خودرو
1  17914401175772326      اهرم
2   2400322364771558      شستا
3  71483646978964608       ذوب
4   7745894403636165      شپنا

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,11000,47,...,0,0,اختيارخ اهرم-11000-1403/11/24,ضهرم1100,12701,1,19620,1,16844,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,14000,110,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,8073,8,0,0,6,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,24000,110,...,0,0,اختيارخ اهرم-24000-1404/01/27,ضهرم0120,6400,20,11999,4,51,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,26000,110,...,0,0,اختيارخ اهرم-26000-1404/01/27,ضهرم0121,1870,1,0,0,2,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,24000,145,...,0,0,اختيارخ اهرم-24000-1404/02/31,ضهرم2016,1000,20,0,0,0,call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1321,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,28000,110,...,0,0,اختيارف اهرم-28000-1404/01/27,طهرم0122,2,20,0,0,0,put
1322,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,30000,75,...,0,0,اختيارف اهرم-30000-1403/12/22,طهرم1245,1029,22,0,0,0,put
1323,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,28000,145,...,0,0,اختيارف اهرم-28000-1404/02/31,طهرم2018,1,100,0,0,0,put
1324,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,30000,145,...,0,0,اختيارف اهرم-30000-1404/02/31,طهرم2019,1,100,0,0,0,put
1325,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250212,34000,47,...,0,0,اختيارف اهرم-34000-1403/11/24,طهرم1113,2099,22,0,0,0,put

In [28]:
for chain in date_chain:
    name = chain.loc[0, "name"]
    jalali_date = name.split("-")[2]
    print("Date: ", jalali_date)
    display(chain)
    print("\n\n")

Date:  1403/10/26

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,10000,19,...,19,5,اختيارخ اهرم-10000-1403/10/26,ضهرم1000,0,0,18699,21,6047,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,10000,19,...,0,0,اختيارف اهرم-10000-1403/10/26,طهرم1000,0,0,0,0,0,put
2,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,11000,19,...,0,0,اختيارف اهرم-11000-1403/10/26,طهرم1001,1,1000,0,0,0,put
3,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,11000,19,...,4,1,اختيارخ اهرم-11000-1403/10/26,ضهرم1001,0,0,0,0,11109,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,12000,19,...,11,2,اختيارخ اهرم-12000-1403/10/26,ضهرم1002,0,0,17999,10,3383,call
5,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,12000,19,...,0,0,اختيارف اهرم-12000-1403/10/26,طهرم1002,1,1000,0,0,50,put
6,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,13000,19,...,0,0,اختيارف اهرم-13000-1403/10/26,طهرم1003,1,1000,0,0,0,put
7,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,13000,19,...,15,2,اختيارخ اهرم-13000-1403/10/26,ضهرم1003,1,1000,17000,41,1049,call
8,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,14000,19,...,0,0,اختيارخ اهرم-14000-1403/10/26,ضهرم1004,0,0,17999,6,4421,call
9,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,14000,19,...,11,1,اختيارف اهرم-14000-1403/10/26,طهرم1004,30,79,53,31,92809,put
10,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,15000,19,...,401,7,اختيارخ اهرم-15000-1403/10/26,ضهرم1005,1400,40,13550,6,10289,call
11,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,15000,19,...,418,20,اختيارف اهرم-15000-1403/10/26,طهرم1005,31,100,49,30,14030,put
12,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,16000,19,...,5616,35,اختيارف اهرم-16000-1403/10/26,طهرم1006,50,1000,63,12,313138,put
13,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,16000,19,...,5879,160,اختيارخ اهرم-16000-1403/10/26,ضهرم1006,12000,66,13331,201,79450,call
14,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,18000,19,...,9086,264,اختيارخ اهرم-18000-1403/10/26,ضهرم1007,10000,99,10199,3,226441,call
15,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,18000,19,...,12044,93,اختيارف اهرم-18000-1403/10/26,طهرم1007,71,440,86,2,210708,put
16,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,20000,19,...,9900,229,اختيارخ اهرم-20000-1403/10/26,ضهرم1008,7999,70,8000,11,129842,call
17,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,20000,19,...,16291,105,اختيارف اهرم-20000-1403/10/26,طهرم1008,72,319,83,8,305236,put
18,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,22000,19,...,50622,241,اختيارف اهرم-22000-1403/10/26,طهرم1009,135,11237,154,252,449684,put
19,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,22000,19,...,10493,275,اختيارخ اهرم-22000-1403/10/26,ضهرم1009,5501,18,5990,7,128712,call
20,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,24000,19,...,15773,304,اختيارخ اهرم-24000-1403/10/26,ضهرم1010,3401,39,4312,12,190180,call
21,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,24000,19,...,25860,248,اختيارف اهرم-24000-1403/10/26,طهرم1010,130,877,140,9,337723,put
22,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,26000,19,...,18463,181,اختيارف اهرم-26000-1403/10/26,طهرم1011,180,100,318,1,135015,put
23,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,26000,19,...,13498,338,اختيارخ اهرم-26000-1403/10/26,ضهرم1011,2400,500,2800,5,244499,call
24,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,28000,19,...,3293,52,اختيارخ اهرم-28000-1403/10/26,ضهرم1012,1300,130,1930,60,73485,call
25,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,28000,19,...,1770,32,اختيارف اهرم-28000-1403/10/26,طهرم1012,1500,1000,1619,7,22062,put
26,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,30000,19,...,0,0,اختيارف اهرم-30000-1403/10/26,طهرم1013,2500,10,0,0,9,put
27,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,30000,19,...,2171,39,اختيارخ اهرم-30000-1403/10/26,ضهرم1013,921,300,1000,46,57344,call
28,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250115,34000,19,...,62,5,اختيارخ اهرم-34000-1403/10/26,ضهرم1014,251,10,345,89,3564,call
29,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250115,34000,19,...,0,0,اختيارف اهرم-34000-1403/10/26,طهرم1014,0,0,0,0,0,put

Date:  1403/11/24

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,11000,47,...,0,0,اختيارخ اهرم-11000-1403/11/24,ضهرم1100,12701,1,19620,1,16844,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,11000,47,...,0,0,اختيارف اهرم-11000-1403/11/24,طهرم1100,1,1000,0,0,0,put
2,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,12000,47,...,6,2,اختيارخ اهرم-12000-1403/11/24,ضهرم1101,16000,25,17000,95,1268,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,12000,47,...,0,0,اختيارف اهرم-12000-1403/11/24,طهرم1101,1,1000,0,0,0,put
4,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,13000,47,...,0,0,اختيارف اهرم-13000-1403/11/24,طهرم1102,0,0,0,0,0,put
5,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,13000,47,...,2,2,اختيارخ اهرم-13000-1403/11/24,ضهرم1102,13300,101,17700,1,1164,call
6,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,14000,47,...,1,1,اختيارخ اهرم-14000-1403/11/24,ضهرم1103,9039,30,0,0,557,call
7,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,14000,47,...,0,0,اختيارف اهرم-14000-1403/11/24,طهرم1103,1,1000,0,0,0,put
8,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,15000,47,...,0,0,اختيارف اهرم-15000-1403/11/24,طهرم1104,0,0,0,0,1000,put
9,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,15000,47,...,10,2,اختيارخ اهرم-15000-1403/11/24,ضهرم1104,8200,2,14995,2,1765,call
10,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,16000,47,...,68,18,اختيارخ اهرم-16000-1403/11/24,ضهرم1105,12500,50,13600,1,9594,call
11,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,16000,47,...,0,0,اختيارف اهرم-16000-1403/11/24,طهرم1105,10,15,0,0,76,put
12,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,18000,47,...,8718,145,اختيارف اهرم-18000-1403/11/24,طهرم1106,180,500,222,577,27114,put
13,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,18000,47,...,2259,103,اختيارخ اهرم-18000-1403/11/24,ضهرم1106,10810,46,11450,5,38958,call
14,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,20000,47,...,3267,97,اختيارخ اهرم-20000-1403/11/24,ضهرم1107,9260,5,9498,23,11171,call
15,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,20000,47,...,155,5,اختيارف اهرم-20000-1403/11/24,طهرم1107,133,10,290,100,806,put
16,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,22000,47,...,106,8,اختيارخ اهرم-22000-1403/11/24,ضهرم1108,7538,1,8099,40,13086,call
17,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,22000,47,...,2872,124,اختيارف اهرم-22000-1403/11/24,طهرم1108,426,61,450,10,9115,put
18,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,24000,47,...,5226,209,اختيارف اهرم-24000-1403/11/24,طهرم1109,790,30,880,269,6318,put
19,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,24000,47,...,1910,151,اختيارخ اهرم-24000-1403/11/24,ضهرم1109,5950,1,6300,61,8662,call
20,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,26000,47,...,82492,3172,اختيارخ اهرم-26000-1403/11/24,ضهرم1110,4581,104,4610,56,75788,call
21,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,26000,47,...,61901,1571,اختيارف اهرم-26000-1403/11/24,طهرم1110,1787,1,1788,6,51719,put
22,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,28000,47,...,2190,125,اختيارخ اهرم-28000-1403/11/24,ضهرم1111,3352,509,3686,30,2209,call
23,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,28000,47,...,1102,9,اختيارف اهرم-28000-1403/11/24,طهرم1111,2450,950,5000,1,1075,put
24,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,30000,47,...,1636,108,اختيارف اهرم-30000-1403/11/24,طهرم1112,3830,49,3999,60,5392,put
25,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,30000,47,...,4079,143,اختيارخ اهرم-30000-1403/11/24,ضهرم1112,2311,81,2449,8,3557,call
26,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250212,34000,47,...,6833,101,اختيارخ اهرم-34000-1403/11/24,ضهرم1113,900,200,984,100,6709,call
27,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250212,34000,47,...,0,0,اختيارف اهرم-34000-1403/11/24,طهرم1113,2099,22,0,0,0,put

Date:  1403/12/22

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,11000,75,...,0,0,اختيارخ اهرم-11000-1403/12/22,ضهرم1233,14000,1,20000,4,1085,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,11000,75,...,0,0,اختيارف اهرم-11000-1403/12/22,طهرم1233,1,1000,0,0,0,put
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,12000,75,...,0,0,اختيارف اهرم-12000-1403/12/22,طهرم1234,1,2000,0,0,0,put
3,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,12000,75,...,6,1,اختيارخ اهرم-12000-1403/12/22,ضهرم1234,10000,41,20110,5,881,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,13000,75,...,0,0,اختيارخ اهرم-13000-1403/12/22,ضهرم1235,13800,2,18340,5,8083,call
5,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,13000,75,...,0,0,اختيارف اهرم-13000-1403/12/22,طهرم1235,0,0,0,0,0,put
6,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,14000,75,...,0,0,اختيارف اهرم-14000-1403/12/22,طهرم1236,1,1000,0,0,0,put
7,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,14000,75,...,6,2,اختيارخ اهرم-14000-1403/12/22,ضهرم1236,8009,40,0,0,352,call
8,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,15000,75,...,0,0,اختيارخ اهرم-15000-1403/12/22,ضهرم1237,11000,3,16000,30,392,call
9,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,15000,75,...,0,0,اختيارف اهرم-15000-1403/12/22,طهرم1237,1,100,0,0,0,put
10,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,16000,75,...,30,1,اختيارخ اهرم-16000-1403/12/22,ضهرم1238,13200,2,15000,23,879,call
11,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,16000,75,...,0,0,اختيارف اهرم-16000-1403/12/22,طهرم1238,1,100,0,0,0,put
12,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,18000,75,...,0,0,اختيارف اهرم-18000-1403/12/22,طهرم1239,1,100,0,0,0,put
13,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,18000,75,...,167,11,اختيارخ اهرم-18000-1403/12/22,ضهرم1239,10050,5,12345,1,4407,call
14,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,20000,75,...,64,3,اختيارخ اهرم-20000-1403/12/22,ضهرم1240,9550,20,10600,1,2906,call
15,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,20000,75,...,0,0,اختيارف اهرم-20000-1403/12/22,طهرم1240,1,25,0,0,0,put
16,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,22000,75,...,1,1,اختيارخ اهرم-22000-1403/12/22,ضهرم1241,7600,5,9771,5,156,call
17,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,22000,75,...,0,0,اختيارف اهرم-22000-1403/12/22,طهرم1241,250,100,0,0,0,put
18,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,24000,75,...,0,0,اختيارف اهرم-24000-1403/12/22,طهرم1242,43,1003,0,0,0,put
19,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,24000,75,...,13236,90,اختيارخ اهرم-24000-1403/12/22,ضهرم1242,6350,98,6900,250,14001,call
20,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,26000,75,...,0,0,اختيارف اهرم-26000-1403/12/22,طهرم1243,601,100,0,0,0,put
21,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,26000,75,...,428,39,اختيارخ اهرم-26000-1403/12/22,ضهرم1243,5103,24,6490,44,4590,call
22,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,28000,75,...,1142,34,اختيارخ اهرم-28000-1403/12/22,ضهرم1244,3830,10,4010,905,4367,call
23,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,28000,75,...,0,0,اختيارف اهرم-28000-1403/12/22,طهرم1244,509,34,0,0,0,put
24,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,30000,75,...,0,0,اختيارف اهرم-30000-1403/12/22,طهرم1245,1029,22,0,0,0,put
25,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,30000,75,...,43,5,اختيارخ اهرم-30000-1403/12/22,ضهرم1245,3051,38,6000,50,315,call
26,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250312,34000,75,...,0,0,اختيارخ اهرم-34000-1403/12/22,ضهرم1246,302,2,0,0,2400,call
27,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250312,34000,75,...,0,0,اختيارف اهرم-34000-1403/12/22,طهرم1246,2099,22,0,0,0,put

Date:  1404/01/27

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,11000,110,...,0,0,اختيارخ اهرم-11000-1404/01/27,ضهرم0111,12050,2,0,0,194,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,11000,110,...,0,0,اختيارف اهرم-11000-1404/01/27,طهرم0111,1,2000,0,0,0,put
2,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,12000,110,...,0,0,اختيارف اهرم-12000-1404/01/27,طهرم0112,1,2000,0,0,0,put
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,12000,110,...,8,1,اختيارخ اهرم-12000-1404/01/27,ضهرم0112,10100,3,0,0,8,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,13000,110,...,0,0,اختيارخ اهرم-13000-1404/01/27,ضهرم0113,11,10,0,0,58,call
5,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,13000,110,...,0,0,اختيارف اهرم-13000-1404/01/27,طهرم0113,1,1000,0,0,0,put
6,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,14000,110,...,0,0,اختيارف اهرم-14000-1404/01/27,طهرم0114,1,1000,0,0,0,put
7,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,14000,110,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,8073,8,0,0,6,call
8,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,15000,110,...,0,0,اختيارف اهرم-15000-1404/01/27,طهرم0115,1,100,0,0,0,put
9,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,15000,110,...,0,0,اختيارخ اهرم-15000-1404/01/27,ضهرم0115,1,100,0,0,0,call
10,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,16000,110,...,10,1,اختيارخ اهرم-16000-1404/01/27,ضهرم0116,2000,1,0,0,25,call
11,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,16000,110,...,0,0,اختيارف اهرم-16000-1404/01/27,طهرم0116,1,100,0,0,0,put
12,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,18000,110,...,0,0,اختيارف اهرم-18000-1404/01/27,طهرم0117,1,100,0,0,0,put
13,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,18000,110,...,0,0,اختيارخ اهرم-18000-1404/01/27,ضهرم0117,1,100,0,0,0,call
14,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,20000,110,...,0,0,اختيارخ اهرم-20000-1404/01/27,ضهرم0118,5000,50,0,0,3016,call
15,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,20000,110,...,0,0,اختيارف اهرم-20000-1404/01/27,طهرم0118,2,10,0,0,0,put
16,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,22000,110,...,0,0,اختيارخ اهرم-22000-1404/01/27,ضهرم0119,4110,2,0,0,123,call
17,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,22000,110,...,0,0,اختيارف اهرم-22000-1404/01/27,طهرم0119,2,10,0,0,0,put
18,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,24000,110,...,0,0,اختيارف اهرم-24000-1404/01/27,طهرم0120,4,10,0,0,0,put
19,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,24000,110,...,0,0,اختيارخ اهرم-24000-1404/01/27,ضهرم0120,6400,20,11999,4,51,call
20,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,26000,110,...,0,0,اختيارف اهرم-26000-1404/01/27,طهرم0121,6,1500,0,0,0,put
21,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,26000,110,...,0,0,اختيارخ اهرم-26000-1404/01/27,ضهرم0121,1870,1,0,0,2,call
22,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,28000,110,...,1,1,اختيارخ اهرم-28000-1404/01/27,ضهرم0122,5012,5,10000,1,535,call
23,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,28000,110,...,0,0,اختيارف اهرم-28000-1404/01/27,طهرم0122,2,20,0,0,0,put
24,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,30000,110,...,0,0,اختيارف اهرم-30000-1404/01/27,طهرم0123,1,100,0,0,0,put
25,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,30000,110,...,0,0,اختيارخ اهرم-30000-1404/01/27,ضهرم0123,90,10,0,0,0,call
26,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,34000,110,...,0,0,اختيارخ اهرم-34000-1404/01/27,ضهرم0124,1,1000,0,0,0,call
27,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,34000,110,...,0,0,اختيارف اهرم-34000-1404/01/27,طهرم0124,0,0,0,0,1,put

Date:  1404/02/31

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,15000,145,...,0,0,اختيارخ اهرم-15000-1404/02/31,ضهرم2011,9001,10,17500,5,309,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,15000,145,...,0,0,اختيارف اهرم-15000-1404/02/31,طهرم2011,1,100,0,0,0,put
2,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,16000,145,...,0,0,اختيارف اهرم-16000-1404/02/31,طهرم2012,1,100,0,0,0,put
3,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,16000,145,...,0,0,اختيارخ اهرم-16000-1404/02/31,ضهرم2012,8001,10,16000,14,136,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,18000,145,...,0,0,اختيارف اهرم-18000-1404/02/31,طهرم2013,1,100,0,0,0,put
5,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,18000,145,...,0,0,اختيارخ اهرم-18000-1404/02/31,ضهرم2013,9556,10,15700,100,0,call
6,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,20000,145,...,0,0,اختيارخ اهرم-20000-1404/02/31,ضهرم2014,5000,5,0,0,0,call
7,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,20000,145,...,0,0,اختيارف اهرم-20000-1404/02/31,طهرم2014,1,100,0,0,0,put
8,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,22000,145,...,0,0,اختيارف اهرم-22000-1404/02/31,طهرم2015,1,100,0,0,0,put
9,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,22000,145,...,0,0,اختيارخ اهرم-22000-1404/02/31,ضهرم2015,3000,5,0,0,0,call
10,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,24000,145,...,0,0,اختيارخ اهرم-24000-1404/02/31,ضهرم2016,1000,20,0,0,0,call
11,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,24000,145,...,0,0,اختيارف اهرم-24000-1404/02/31,طهرم2016,1,100,0,0,0,put
12,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,26000,145,...,0,0,اختيارخ اهرم-26000-1404/02/31,ضهرم2017,100,100,0,0,0,call
13,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,26000,145,...,0,0,اختيارف اهرم-26000-1404/02/31,طهرم2017,1,100,0,0,0,put
14,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,28000,145,...,0,0,اختيارخ اهرم-28000-1404/02/31,ضهرم2018,400,50,0,0,0,call
15,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,28000,145,...,0,0,اختيارف اهرم-28000-1404/02/31,طهرم2018,1,100,0,0,0,put
16,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,30000,145,...,0,0,اختيارخ اهرم-30000-1404/02/31,ضهرم2019,100,100,0,0,0,call
17,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,30000,145,...,0,0,اختيارف اهرم-30000-1404/02/31,طهرم2019,1,100,0,0,0,put
18,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,34000,145,...,1,1,اختيارخ اهرم-34000-1404/02/31,ضهرم2020,1350,14,0,0,12,call
19,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,34000,145,...,0,0,اختيارف اهرم-34000-1404/02/31,طهرم2020,1,100,0,0,0,put
20,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,38000,145,...,0,0,اختيارف اهرم-38000-1404/02/31,طهرم2021,1,100,0,0,0,put
21,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,38000,145,...,4,4,اختيارخ اهرم-38000-1404/02/31,ضهرم2021,905,13,14990,47,34,call
22,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,42000,145,...,49,7,اختيارخ اهرم-42000-1404/02/31,ضهرم2022,1050,5,2500,5,100,call
23,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,42000,145,...,0,0,اختيارف اهرم-42000-1404/02/31,طهرم2022,2000,10,0,0,0,put

In [23]:
for chain in strike_price_chain:
    print("Strike Price: ", chain.loc[0, "strike_price"])
    display(chain)
    print("\n\n")

Strike Price:  10000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,10000,19,...,19,5,اختيارخ اهرم-10000-1403/10/26,ضهرم1000,0,0,18699,21,6047,call

Strike Price:  11000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,11000,19,...,4,1,اختيارخ اهرم-11000-1403/10/26,ضهرم1001,0,0,0,0,11109,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,11000,47,...,0,0,اختيارخ اهرم-11000-1403/11/24,ضهرم1100,12701,1,19620,1,16844,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,11000,75,...,0,0,اختيارخ اهرم-11000-1403/12/22,ضهرم1233,14000,1,20000,4,1085,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,11000,110,...,0,0,اختيارخ اهرم-11000-1404/01/27,ضهرم0111,12050,2,0,0,194,call

Strike Price:  12000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,12000,19,...,11,2,اختيارخ اهرم-12000-1403/10/26,ضهرم1002,0,0,17999,10,3383,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,12000,47,...,6,2,اختيارخ اهرم-12000-1403/11/24,ضهرم1101,16000,25,17000,95,1268,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,12000,75,...,6,1,اختيارخ اهرم-12000-1403/12/22,ضهرم1234,10000,41,20110,5,881,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,12000,110,...,8,1,اختيارخ اهرم-12000-1404/01/27,ضهرم0112,10100,3,0,0,8,call

Strike Price:  13000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,13000,19,...,15,2,اختيارخ اهرم-13000-1403/10/26,ضهرم1003,1,1000,17000,41,1049,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,13000,47,...,2,2,اختيارخ اهرم-13000-1403/11/24,ضهرم1102,13300,101,17700,1,1164,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,13000,75,...,0,0,اختيارخ اهرم-13000-1403/12/22,ضهرم1235,13800,2,18340,5,8083,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,13000,110,...,0,0,اختيارخ اهرم-13000-1404/01/27,ضهرم0113,11,10,0,0,58,call

Strike Price:  14000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,14000,19,...,0,0,اختيارخ اهرم-14000-1403/10/26,ضهرم1004,0,0,17999,6,4421,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,14000,47,...,1,1,اختيارخ اهرم-14000-1403/11/24,ضهرم1103,9039,30,0,0,557,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,14000,75,...,6,2,اختيارخ اهرم-14000-1403/12/22,ضهرم1236,8009,40,0,0,352,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,14000,110,...,0,0,اختيارخ اهرم-14000-1404/01/27,ضهرم0114,8073,8,0,0,6,call

Strike Price:  15000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,15000,19,...,401,7,اختيارخ اهرم-15000-1403/10/26,ضهرم1005,1400,40,13550,6,10289,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,15000,47,...,10,2,اختيارخ اهرم-15000-1403/11/24,ضهرم1104,8200,2,14995,2,1765,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,15000,75,...,0,0,اختيارخ اهرم-15000-1403/12/22,ضهرم1237,11000,3,16000,30,392,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,15000,110,...,0,0,اختيارخ اهرم-15000-1404/01/27,ضهرم0115,1,100,0,0,0,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,15000,145,...,0,0,اختيارخ اهرم-15000-1404/02/31,ضهرم2011,9001,10,17500,5,309,call

Strike Price:  16000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,16000,19,...,5879,160,اختيارخ اهرم-16000-1403/10/26,ضهرم1006,12000,66,13331,201,79450,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,16000,47,...,68,18,اختيارخ اهرم-16000-1403/11/24,ضهرم1105,12500,50,13600,1,9594,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,16000,75,...,30,1,اختيارخ اهرم-16000-1403/12/22,ضهرم1238,13200,2,15000,23,879,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,16000,110,...,10,1,اختيارخ اهرم-16000-1404/01/27,ضهرم0116,2000,1,0,0,25,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,16000,145,...,0,0,اختيارخ اهرم-16000-1404/02/31,ضهرم2012,8001,10,16000,14,136,call

Strike Price:  18000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,18000,19,...,9086,264,اختيارخ اهرم-18000-1403/10/26,ضهرم1007,10000,99,10199,3,226441,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,18000,47,...,2259,103,اختيارخ اهرم-18000-1403/11/24,ضهرم1106,10810,46,11450,5,38958,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,18000,75,...,167,11,اختيارخ اهرم-18000-1403/12/22,ضهرم1239,10050,5,12345,1,4407,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,18000,110,...,0,0,اختيارخ اهرم-18000-1404/01/27,ضهرم0117,1,100,0,0,0,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,18000,145,...,0,0,اختيارخ اهرم-18000-1404/02/31,ضهرم2013,9556,10,15700,100,0,call

Strike Price:  20000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,20000,19,...,9900,229,اختيارخ اهرم-20000-1403/10/26,ضهرم1008,7999,70,8000,11,129842,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,20000,47,...,3267,97,اختيارخ اهرم-20000-1403/11/24,ضهرم1107,9260,5,9498,23,11171,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,20000,75,...,64,3,اختيارخ اهرم-20000-1403/12/22,ضهرم1240,9550,20,10600,1,2906,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,20000,110,...,0,0,اختيارخ اهرم-20000-1404/01/27,ضهرم0118,5000,50,0,0,3016,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,20000,145,...,0,0,اختيارخ اهرم-20000-1404/02/31,ضهرم2014,5000,5,0,0,0,call

Strike Price:  22000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,22000,19,...,10493,275,اختيارخ اهرم-22000-1403/10/26,ضهرم1009,5501,18,5990,7,128712,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,22000,47,...,106,8,اختيارخ اهرم-22000-1403/11/24,ضهرم1108,7538,1,8099,40,13086,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,22000,75,...,1,1,اختيارخ اهرم-22000-1403/12/22,ضهرم1241,7600,5,9771,5,156,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,22000,110,...,0,0,اختيارخ اهرم-22000-1404/01/27,ضهرم0119,4110,2,0,0,123,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,22000,145,...,0,0,اختيارخ اهرم-22000-1404/02/31,ضهرم2015,3000,5,0,0,0,call

Strike Price:  24000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,24000,19,...,15773,304,اختيارخ اهرم-24000-1403/10/26,ضهرم1010,3401,39,4312,12,190180,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,24000,47,...,1910,151,اختيارخ اهرم-24000-1403/11/24,ضهرم1109,5950,1,6300,61,8662,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,24000,75,...,13236,90,اختيارخ اهرم-24000-1403/12/22,ضهرم1242,6350,98,6900,250,14001,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,24000,110,...,0,0,اختيارخ اهرم-24000-1404/01/27,ضهرم0120,6400,20,11999,4,51,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,24000,145,...,0,0,اختيارخ اهرم-24000-1404/02/31,ضهرم2016,1000,20,0,0,0,call

Strike Price:  26000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20240824,20250115,26000,19,...,13498,338,اختيارخ اهرم-26000-1403/10/26,ضهرم1011,2400,500,2800,5,244499,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20240922,20250212,26000,47,...,82492,3172,اختيارخ اهرم-26000-1403/11/24,ضهرم1110,4581,104,4610,56,75788,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241019,20250312,26000,75,...,428,39,اختيارخ اهرم-26000-1403/12/22,ضهرم1243,5103,24,6490,44,4590,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,26000,110,...,0,0,اختيارخ اهرم-26000-1404/01/27,ضهرم0121,1870,1,0,0,2,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,26000,145,...,0,0,اختيارخ اهرم-26000-1404/02/31,ضهرم2017,100,100,0,0,0,call

Strike Price:  28000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,28000,19,...,3293,52,اختيارخ اهرم-28000-1403/10/26,ضهرم1012,1300,130,1930,60,73485,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,28000,47,...,2190,125,اختيارخ اهرم-28000-1403/11/24,ضهرم1111,3352,509,3686,30,2209,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,28000,75,...,1142,34,اختيارخ اهرم-28000-1403/12/22,ضهرم1244,3830,10,4010,905,4367,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241123,20250416,28000,110,...,1,1,اختيارخ اهرم-28000-1404/01/27,ضهرم0122,5012,5,10000,1,535,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,28000,145,...,0,0,اختيارخ اهرم-28000-1404/02/31,ضهرم2018,400,50,0,0,0,call

Strike Price:  30000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250115,30000,19,...,2171,39,اختيارخ اهرم-30000-1403/10/26,ضهرم1013,921,300,1000,46,57344,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250212,30000,47,...,4079,143,اختيارخ اهرم-30000-1403/11/24,ضهرم1112,2311,81,2449,8,3557,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241215,20250312,30000,75,...,43,5,اختيارخ اهرم-30000-1403/12/22,ضهرم1245,3051,38,6000,50,315,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,30000,110,...,0,0,اختيارخ اهرم-30000-1404/01/27,ضهرم0123,90,10,0,0,0,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,30000,145,...,0,0,اختيارخ اهرم-30000-1404/02/31,ضهرم2019,100,100,0,0,0,call

Strike Price:  34000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250115,34000,19,...,62,5,اختيارخ اهرم-34000-1403/10/26,ضهرم1014,251,10,345,89,3564,call
1,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250212,34000,47,...,6833,101,اختيارخ اهرم-34000-1403/11/24,ضهرم1113,900,200,984,100,6709,call
2,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250312,34000,75,...,0,0,اختيارخ اهرم-34000-1403/12/22,ضهرم1246,302,2,0,0,2400,call
3,1000,17914401175772326,اهرم,28270,28010,28470,20241223,20250416,34000,110,...,0,0,اختيارخ اهرم-34000-1404/01/27,ضهرم0124,1,1000,0,0,0,call
4,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,34000,145,...,1,1,اختيارخ اهرم-34000-1404/02/31,ضهرم2020,1350,14,0,0,12,call

Strike Price:  38000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,38000,145,...,4,4,اختيارخ اهرم-38000-1404/02/31,ضهرم2021,905,13,14990,47,34,call

Strike Price:  42000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,28270,28010,28470,20241221,20250521,42000,145,...,49,7,اختيارخ اهرم-42000-1404/02/31,ضهرم2022,1050,5,2500,5,100,call

### Tadbir API
Provides low latency and more detailed data (such as initial margin and order book). This may be suitable for obtaining data for actual trading.

In [17]:
from tseopt import tadbir_api

from pprint import pprint

isin_list = ["IRO9AHRM2501", "IROATVAF0621", "IRO9BMLT2771", "IRO9TAMN8991", "IRO9IKCO81M1"]

bulk_data = tadbir_api.get_last_bulk_data(isin_list=isin_list)
detail_data = tadbir_api.get_detail_data(isin_list[0])
symbol_info = detail_data.get("symbol_info")
order_book = pd.DataFrame(detail_data.get("order_book"))

display(bulk_data)

pprint(symbol_info)
display(order_book)

,BasisVolume,ClosingPrice,CompanyName,BestBuyPrice,BestBuyQuantity,BestSellPrice,BestSellQuantity,NoBestBuy,NoBestSell,FirstTradedPrice,...,TotalTradeValue,TradeDate,varSign,ClosingPriceVar,ClosingPriceVarPercent,LastTradedPriceVar,LastTradedPriceVarPercent,tse_code,SectorCodeId,cs
0,1.0,12503.0,اختیارخ اهرم-16000-1403/11/24,12500.0,50,13600.0,1,1,1,12011.0,...,850184000.0,1403/10/5 12:28,1,-1056.0,-7.79,-957.0,-7.06,18154069997422059,None,1000
1,1.0,9335.0,اختیارخ توان-16000-14031002,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/10/2 12:29,-1,0.0,0.00,0.0,0.00,14732757416991570,None,1000
2,1.0,1700.0,اختیارخ وبملت-1800-1403/11/24,100.0,30,11000.0,30,1,1,0.0,...,0.0,1403/10/2 11:50,0,0.0,0.00,0.0,0.00,48841241645050970,None,1000
3,1.0,98.0,اختیارخ شستا-850-1403/08/09,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/8/9 12:29,0,0.0,0.00,0.0,0.00,18794200601794224,None,1000
4,1.0,1.0,اختیارخ خودرو-4000-1403/03/09,0.0,0,0.0,0,0,0,0.0,...,0.0,1403/3/9 10:29,0,0.0,0.00,0.0,0.00,414085078149021,None,1000

{'BaseVolume': 1,
 'CP12': 0,
 'ClosingPrice': 12503.0,
 'CompanyTitle': 'اختیارخ اهرم-16000-1403/11/24',
 'GroupStateID': 8,
 'HighAllowedPrice': 500000.0,
 'HighPrice': 13498.0,
 'InstrumentCode': '18154069997422059',
 'IsCautionAgreement': False,
 'IsSepahAgreement': False,
 'LastTradedPrice': 12602.0,
 'LotSize': 1,
 'LowAllowedPrice': 1.0,
 'LowPercent': 100,
 'LowPrice': 12011.0,
 'MarketType': 'MarketType.BuyOption',
 'MaxPercent': 3588,
 'MaxQuantityOrder': 1000,
 'MinQuantityOrder': 1,
 'NSCCode': 'IRO9AHRM2501',
 'RefPrice': 13559.0,
 'Symbol': 'ضهرم1105',
 'SymbolStateId': 1,
 'TickSize': 1.0,
 'TotalNumberOfSharesTraded': 68,
 'TotalNumberOfTrades': 18,
 'TotalTradeValue': 850184000.0,
 'TradeDate': '1403/10/05 - 12:28:40',
 'UA_LastTradedPrice': 28010.0,
 'UA_isin': 'IRT1AHRM0001',
 'YesterdayPrice': 13559.0,
 'contractSize': 1000,
 'contractStartDate': '1403/07/01',
 'cpv': -1056.0,
 'cpvp': -7.79,
 'crn': 'ریال',
 'crp': 1,
 'exerciseDate': '1403/11/24',
 'gc': '3A',
 'initial_margin': 5660000.0,
 'iso': True,
 'lpv': -957.0,
 'lpvp': -7.06,
 'mbop': 0,
 'mcaop': 112000,
 'mcop': 112000,
 'mmop': 2250000,
 'openPositionNum': 9594,
 'pv': 0.0,
 'rm': 18163000.0,
 'strikePrice': 16000.0,
 'th': 461110.0,
 'tl': 0.0,
 'vs': 1}

,BestBuyPrice,BestSellPrice,BestSellQuantity,BestBuyQuantity,NoBestBuy,NoBestSell,NSCCode,Place
0,12500.0,13600.0,1,50,1,1,IRO9AHRM2501,1
1,12195.0,13700.0,10,20,1,1,IRO9AHRM2501,2
2,12021.0,13800.0,13,2,1,2,IRO9AHRM2501,3
3,12011.0,15800.0,12,3,2,1,IRO9AHRM2501,4
4,12010.0,0.0,0,1,1,0,IRO9AHRM2501,5

### Mercantile Exchange
Fetches all data which mercantile exchange website provides.

In [30]:
from tseopt import make_a_mercantile_data_object


md = make_a_mercantile_data_object()
md.update_data(timeout=20)
print(md.gavahi[0])
print(md.sandoq[0])
print(md.salaf[0])
print(md.cdc[0])
print(md.all_market)
print(md.future_date_time)
print(md.future[0])
print(md.markets_info[0])

IndexError: list index out of range

#### Gavahi

In [6]:
display(pd.DataFrame(md.gavahi).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,16255851958781005,IRK1K01103C4,سكه0312پ01,تمام سكه طرح جديد0312 رفاه,5418557.0,5433681.0,5450001.0,31444.0,5469000.0,5411114.0,...,318,0,261600.0,0.0,244,2,111800.0,149800.0,0001-01-01T00:00:00,15:00:43
1,31447590411939048,IRK1K01704C9,سكه0412پ03,تمام سكه طرح جديد0412 سامان,5414691.0,5437168.0,5447500.0,32809.0,5470000.0,5410106.0,...,113,0,54500.0,0.0,59,2,23400.0,31100.0,0001-01-01T00:00:00,15:00:43
2,71448561759885455,IRK1K01403A2,سكه0310پ04,تمام سكه طرح جديد 0310 صادرات,5409779.0,5423933.0,5440000.0,30221.0,5475985.0,5378001.0,...,56,0,36200.0,0.0,61,1,30300.0,5900.0,0001-01-01T00:00:00,15:00:43
3,62180931969029505,IRK1K01604B3,سكه0411پ05,تمام سكه طرح جديد0411 آينده,5416522.0,5440231.0,5430060.0,13538.0,5479999.0,5410000.0,...,40,0,15100.0,0.0,43,1,11700.0,3400.0,0001-01-01T00:00:00,14:59:43
4,66776904822812259,IRK1A11504A7,زعف0410پ09,زعفران0410نگين نوين(پ),839881.0,850878.0,860000.0,20119.0,848000.0,844900.0,...,2,1,2082.0,148158.0,35,1,148368.0,1872.0,0001-01-01T00:00:00,15:00:43

#### Sandoq

In [7]:
display(pd.DataFrame(md.sandoq).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,34144395039913458,IRTKMOFD0006,عيار,صندوق طلاي عيار مفيد,143032.0,143578.0,143060.0,28.0,145050.0,142550.0,...,16242,28,66713016.0,2605838.0,5222,9,43757955.0,25560899.0,0001-01-01T00:00:00,15:00:43
1,46700660505281786,IRTKLOTF0009,طلا,صندوق س.پشتوانه طلاي لوتوس,369794.0,372572.0,372151.0,2357.0,376000.0,370980.0,...,5909,23,7641743.0,3100170.0,3187,4,10600161.0,141752.0,0001-01-01T00:00:00,15:00:43
2,25559236668122210,IRTKROBA0008,كهربا,صندوق س.پشتوانه سكه طلا كهربا,49434.0,49754.0,49710.0,276.0,50001.0,49510.0,...,3651,10,37362483.0,3488438.0,1674,4,38927847.0,1923074.0,0001-01-01T00:00:00,15:00:43
3,32469128621155736,IRTKZARA0006,مثقال,صندوق س.پشتوانه طلاي زرين آگاه,41028.0,41248.0,41159.0,131.0,41400.0,41131.0,...,2582,7,18274295.0,3113621.0,927,5,19892926.0,1494990.0,0001-01-01T00:00:00,15:00:43
4,58514988269776425,IRTKGANJ0004,گنج,صندوق س. طلا كيميا زرين كاردان,44677.0,44876.0,44830.0,153.0,45065.0,44740.0,...,2050,7,16181066.0,327418.0,925,2,16087234.0,421250.0,0001-01-01T00:00:00,15:00:43

#### Salaf

In [8]:
display(pd.DataFrame(md.salaf).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,28119534882897713,IRBKKER104B8,عكرمان1,سلف كي ام سي كرمان موتور,1829039.0,1824000.0,1824000.0,-5039.0,1824000.0,1824000.0,...,0,1,0.0,3109.0,1,0,3109.0,0.0,0001-01-01T00:00:00,08:59:06
1,37997914552081987,IRBKKER204B6,عكرمان2,خودرو كي ام سي كرمان موتور,1745848.0,1754980.0,1754980.0,9132.0,1754980.0,1754980.0,...,1,0,4.0,0.0,0,1,0.0,4.0,0001-01-01T00:00:00,11:33:35
2,30180206509447855,IRBKBTRY0518,عباتري,سلف موازي باتري55 آمپر كرمان,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,09:27:16
3,13191051508594726,IRBKSNG504A5,عسنگ5,سلف موازي استاندارد آهن مركزي,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,09:12:16
4,6366366216425323,IRBKSAEB0579,عصائب,سلف موازي ميلگرد صائب تبريز,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:59:06

#### Future

In [9]:
display(pd.DataFrame(md.future).head(5))

,ContractID,LastTradingDate,ContractCode,ContractDescription,ContractSize,ContractSizeUnitFaDesc,ContractSizeUnitEnDesc,ContractCurrencyFaDesc,ContractCurrencyEnDesc,ContractCurrencyDecimalPlaces,...,LegalBuyerCount,LegalSellerCount,NaturalBuyerCount,NaturalSellerCount,TodayLiveSettlement,TradeCount,TradeVolume,PersianOrdersDateTime,PersianLastSettlementPriceDate,PesrsianLastTradingDate
0,278,2025-01-08T00:00:00,ETCDY03,قرارداد آتی صندوق طلای لوتوس تحویل دی ماه 1403,1000.0,واحد,-,ریال,Rials,None,...,2,0,31,45,3.838865e+05,136,257,None,None,None
1,284,2025-04-15T00:00:00,ETCFA04,قرارداد آتی صندوق طلای لوتوس تحویل فروردین ماه...,1000.0,واحد,-,ریال,Rials,None,...,0,0,56,49,4.440096e+05,219,312,None,None,None
2,285,2025-03-02T00:00:00,KBES03,قرارداد آتی صندوق طلای کهربا تحویل اسفند ماه 1...,1000.0,واحد,-,ریال,Rials,None,...,1,1,34,24,5.433274e+04,143,357,None,None,None
3,288,2024-12-25T00:00:00,SAFDY03,قرارداد آتی زعفران نگین تحویل دی ماه 1403,100.0,گرم,-,ریال,Rials,None,...,1,3,35,40,8.138720e+05,787,6867,None,None,None
4,289,2025-02-17T00:00:00,GB29BA03,قرارداد آتی شمش طلای خام 995 تحویل بهمن ماه 1403,1.0,گرم,-,ریال,Rials,None,...,0,2,19,12,7.437707e+07,86,193,None,None,None

#### CDC

In [10]:
display(pd.DataFrame(md.cdc).head(5))

,ContractID,ContractCode,ContractDescription,LastTradingPersianDate,ContractSize,ContractSizeUnitFaDesc,TotalAssetChangesColor,ContractCurrencyFaDesc,LastSettlementPrice,AskPrice1,...,OrdersPersianDateTime,OrdersDateTime,OrdersCounter,CommodityID,CommodityName,CommodityColor,CommodityColor1,TradesCounter,IsOrdersHighLight,IsTradesHighLight
0,43,CD1SIB0001,گواهی سپرده پیوسته شمش نقره 999.9,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Red,ریال,949924.0,0.0,...,16:59:51,2024-12-24T16:59:51.027,-1,21,شمش نقره,#F0F0F0,#E3E3E3,-1,False,False
1,42,CD1GOC0001,گواهی سپرده پیوسته تمام سکه بهار آزادی طرح جدید,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Green,ریال,549533647.0,0.0,...,16:59:28,2024-12-24T16:59:28.647,-1,4,سکه طلا,#64ffffce,#ffefef15,-1,False,False
2,41,CD1GOB0001,گواهی سپرده پیوسته شمش طلای +995,1410/12/01,10.0,ضریب تبدیل نماد به گروه انبار,Green,ریال,6752365.0,0.0,...,16:59:58,2024-12-24T16:59:58.913,-1,2,شمش طلا,#fdf5e6,#fdf5e6,-1,False,False

#### markets_info

In [11]:
display(pd.DataFrame(md.markets_info).head(5))

,_StrikeLevel,_StrikePrice,_LastUpdate,_PutContractVisibility,_ContractCategory,_CommodityGroup,_ContractSubGroup,_CallContractID,_CallContractCode,_CallContractDescription,...,PutTradesVolume,PutTradesVolumeVisibility,PutTradesValue,PutTradesValueCurrencyFaDesc,PutTradesValueCurrencyEnDesc,PutOpenInterests,PutOpenInterestsChanges,PutOpenInterestsChangesPercent,PutOpenInterestsChangesVisibility,PutOpenInterestsChangesColor
0,-1,300000.0,2024-12-02T17:00:03.41,Visible,DY03\t\t\tتاریخ سررسید: 1403/10/16,ETCDY03,ETCDY03,1001126,FEDY03C30,قرارداد اختیار معامله خرید مبتنی بر قرارداد آت...,...,NaN,Collapsed,NaN,,,NaN,NaN,0.0,Collapsed,Gray
1,0,330000.0,2024-12-02T17:00:03.41,Visible,DY03\t\t\tتاریخ سررسید: 1403/10/16,ETCDY03,ETCDY03,1001127,FEDY03C33,قرارداد اختیار معامله خرید مبتنی بر قرارداد آت...,...,NaN,Collapsed,NaN,,,NaN,NaN,0.0,Collapsed,Gray
2,1,360000.0,2024-12-02T17:00:03.41,Visible,DY03\t\t\tتاریخ سررسید: 1403/10/16,ETCDY03,ETCDY03,1001128,FEDY03C36,قرارداد اختیار معامله خرید مبتنی بر قرارداد آت...,...,NaN,Collapsed,NaN,,,NaN,NaN,0.0,Collapsed,Gray
3,-1,4600000.0,2024-12-02T17:00:03.413,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001150,GBBA03C460,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,NaN,Collapsed,NaN,,,NaN,NaN,0.0,Collapsed,Gray
4,0,4800000.0,2024-12-02T17:00:03.413,Visible,BA03\t\t\tتاریخ سررسید: 1403/11/27,CDC,CDCBA03,1001152,GBBA03C480,قرارداد اختیار معامله خرید شمش طلا سررسید بهمن...,...,NaN,Collapsed,NaN,,,NaN,NaN,0.0,Collapsed,Gray