# TSELiveOptionData

----
This repository contains code for fetching and processing live option data from various public APIs.



## How to Use This Repository

---

First, ensure that you have Python version 3.12 or higher installed. After that, you must install the dependencies with the following command:

`pip install -r requirements.txt`

## Project Structure

---
The project consists of two main directories: `data_source` and `use_case`. The `data_source` directory contains code for interacting with public APIs, while the `use_case` directory includes independent modules that utilize raw data from the data sources.



## Data Sources

---
| Source            | Description                                                                                                                                    |
|-------------------|------------------------------------------------------------------------------------------------------------------------------------------------|
| TSETMC Website    |Fetches all Bourse and FaraBours data (suitable for screening the total market).                                                               |
| Tadbir Public API | Provides low latency and more detailed data (such as initial margin and order book). This may be suitable for obtaining data for actual trading. |



## Use cases

---

Currently, this directory contains only one module, `screen_market.py`, but it will be expanded in the future!



### screen_market
The `screen_market.py` file serves as an example demonstrating the use case of the TSETMC website data. It showcases how to create an instance of the `OptionMarket` class, analyze option market data, and print various metrics related to option trading.




## Technical Terms

---

| English Word           | Farsi Translation           |
|-----------------------|-----------------------------|
| ua_tse_code           | کد نماد دارایی پایه         |
| ua_ticker             | نماد معاملاتی دارایی پایه   |
| days_to_maturity      | روزهای باقی‌مانده تا سررسید |
| strike_price          | قیمت اعمال                  |
| contract_size         | اندازه قرارداد              |
| ua_close_price        | قیمت پایانی دارایی پایه     |
| ua_yesterday_price    | قیمت روز گذشته دارایی پایه  |
| begin_date            | تاریخ شروع قرارداد          |
| end_date              | تاریخ سررسید قرارداد        |
| tse_code              | کد نماد آپشن                |
| ticker                | نماد معاملاتی آپشن              |
| trades_num            | تعداد معاملات آپشن              |
| trades_volume         | حجم معاملات آپشن                |
| trades_value          | ارزش معاملات آپشن               |
| last_price            | آخرین قیمت آپشن                 |
| close_price           | قیمت پایانی آپشن                |
| yesterday_price       | قیمت روز گذشته آپشن             |
| open_positions        | موقعیت‌های باز              |
| yesterday_open_positions | موقعیت‌های باز روز گذشته    |
| notional_value        | ارزش اسمی                   |
| bid_price             | قیمت پیشنهادی خرید          |
| bid_volume            | حجم پیشنهادی خرید           |
| ask_price             | قیمت پیشنهادی فروش          |
| ask_volume            | حجم پیشنهادی فروش           |

# Usage

In [1]:
from IPython.display import display
import pandas as pd

# TSETMC Website API

In [ ]:
from data_source.tsetmc.api import fetch_cleaned_entire_market_data

read_data_from_file = True
# read_data_from_file = False

csv_file_path = r"data_source\tsetmc\TSETMC_sample_data.csv"

if read_data_from_file:
    entire_option_market_data = pd.read_csv(csv_file_path)
else:
    entire_option_market_data = fetch_cleaned_entire_market_data()
    entire_option_market_data.to_csv(path_or_buf=csv_file_path, index=False)


display(entire_option_market_data)
print(entire_option_market_data.iloc[0])

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,tse_code,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,16570,16120,20240615,20241120,20000,8,43072367801777779,...,19087,122,اختيارخ اهرم-20000-1403/08/30,ضهرم8005,12,50,16,1249,246240,call
1,1000,43443105991896600,ارزش,18550,18110,20240817,20241215,18000,33,43060893718114997,...,0,0,اختيارخ ارزش-18000-1403/09/25,ضارش9006,11,200,0,0,409,call
2,1000,44604318643489231,بيدار,7870,7660,20241009,20250108,10000,57,40446253344612873,...,0,0,اختيارخ بيدار-10000-1403/10/19,ضبيد1006,1,300,300,200,503,call
3,1000,778253364357513,وبملت,2204,2143,20240817,20241218,1500,36,17640843853734260,...,0,0,اختيارخ وبملت-1500-1403/09/28,ضملت9013,50,180,1000,1000,43062,call
4,1000,778253364357513,وبملت,2204,2143,20240817,20241218,1800,36,62195326705007487,...,0,0,اختيارخ وبملت-1800-1403/09/28,ضملت9016,0,0,690,10,304,call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1977,10,67522512921942106,پادا,149245,149008,20240707,20250105,190000,54,40489538509583284,...,0,0,اختيارف پادا-190000-14031016,طپادا1010,100,1000,0,0,0,put
1978,1000,25211433301660888,خپارس,752,731,20241015,20241201,700,19,64999726043881502,...,0,0,اختيارف خپارس-700-14030911,طخپارس902,0,0,0,0,0,put
1979,1000,25211433301660888,خپارس,752,731,20241015,20241201,800,19,66718346568169696,...,0,0,اختيارف خپارس-800-14030911,طخپارس904,0,0,0,0,0,put
1980,1000,25211433301660888,خپارس,752,731,20241015,20250202,600,82,31096670670746865,...,0,0,اختيارف خپارس-600-14031114,طخپارس1100,0,0,0,0,0,put
1981,1000,53059909885484371,رويين,10437,10371,20240917,20250209,12000,89,20606279281243326,...,0,0,اختيارف رويين-12000-14031121,طرويين1106,0,0,0,0,0,put

contract_size                                        1000
ua_tse_code                             17914401175772326
ua_ticker                                            اهرم
ua_close_price                                      16570
ua_yesterday_price                                  16120
begin_date                                       20240615
end_date                                         20241120
strike_price                                        20000
days_to_maturity                                        8
tse_code                                43072367801777779
last_price                                             16
open_positions                                     246240
close_price                                            14
yesterday_price                                        24
notional_value                             316271590000.0
trades_value                                  258156000.0
trades_volume                                       19087
trades_num                                            122
name                        اختيارخ اهرم-20000-1403/08/30
ticker                                           ضهرم8005
bid_price                                              12
bid_volume                                             50
ask_price                                              16
ask_volume                                           1249
yesterday_open_positions                           246240
option_type                                          call
Name: 0, dtype: object

# Screen Market

In [5]:
from use_case.screen_market import OptionMarket, convert_to_billion_toman

option_market = OptionMarket(entire_option_market_data=entire_option_market_data)

print(f"total_trade_value: {option_market.total_trade_value / 1e10:.0f} B Toman", end="\n\n")

most_trade_value_calls = pd.DataFrame(option_market.most_trade_value.get("call"))
most_trade_value_calls['ticker'] = most_trade_value_calls['ticker'].astype(str)
most_trade_value_calls["trades_value"] = convert_to_billion_toman(most_trade_value_calls["trades_value"])


most_trade_value_puts = pd.DataFrame(option_market.most_trade_value.get("put"))
most_trade_value_puts['ticker'] = most_trade_value_puts['ticker'].astype(str)
most_trade_value_puts["trades_value"] = convert_to_billion_toman(most_trade_value_puts["trades_value"])


most_trade_value_by_underlying_asset = pd.DataFrame(option_market.most_trade_value_by_underlying_asset)
most_trade_value_by_underlying_asset[["call", "put", "total"]] =convert_to_billion_toman(most_trade_value_by_underlying_asset[["call", "put", "total"]])


display(most_trade_value_calls)
display(most_trade_value_puts)
display(most_trade_value_by_underlying_asset)

total_trade_value: 287 B Toman

     ticker   trades_value
0  ضهرم9003  64.77 B Toman
1  ضخود9027  29.09 B Toman
2  ضخود9026  24.23 B Toman
3  ضهرم8003  20.44 B Toman
4  ضهرم9004   7.51 B Toman

     ticker   trades_value
0  طهرم9003  35.83 B Toman
1  طخود9027  13.32 B Toman
2  طخود9026   7.85 B Toman
3  طهرم8003   6.19 B Toman
4  طهرم9004   5.56 B Toman

  ua_ticker            call            put           total
0      اهرم  107.75 B Toman  56.02 B Toman  163.77 B Toman
1     خودرو   76.91 B Toman  22.03 B Toman   98.95 B Toman
2      شستا    8.33 B Toman   0.57 B Toman    8.89 B Toman
3     خساپا    3.31 B Toman    0.0 B Toman    3.31 B Toman
4      توان    2.77 B Toman   0.02 B Toman    2.78 B Toman

# Tadbir API

In [6]:
from data_source.tadbir.api import tadbir_api

from pprint import pprint

isin_list = ["IRO9AHRM2501", "IROATVAF0621", "IRO9BMLT2771", "IRO9TAMN8991", "IRO9IKCO81M1"]

bulk_data = tadbir_api.get_last_bulk_data(isin_list=isin_list)
detail_data = tadbir_api.get_detail_data(isin_list[0])
symbol_info = detail_data.get("symbol_info")
order_book = pd.DataFrame(detail_data.get("order_book"))

display(bulk_data)

pprint(symbol_info)
display(order_book)

,BasisVolume,ClosingPrice,CompanyName,BestBuyPrice,BestBuyQuantity,BestSellPrice,BestSellQuantity,NoBestBuy,NoBestSell,FirstTradedPrice,...,TotalTradeValue,TradeDate,varSign,ClosingPriceVar,ClosingPriceVarPercent,LastTradedPriceVar,LastTradedPriceVarPercent,tse_code,SectorCodeId,cs
0,1.0,1798.0,اختیارخ اهرم-16000-1403/11/24,1626.0,20,1980.0,75,1,2,1800.0,...,4.297640e+08,1403/8/21 12:13,0,-272.0,-13.14,-419.0,-20.24,18154069997422059,None,1000
1,1.0,1305.0,اختیارخ توان-16000-14031002,1250.0,20,1340.0,121,1,1,1401.0,...,2.764052e+09,1403/8/21 12:27,0,-10.0,-0.76,-125.0,-9.51,14732757416991570,None,1000
2,1.0,355.0,اختیارخ وبملت-1800-1403/11/24,177.0,1,0.0,0,1,0,0.0,...,0.000000e+00,1403/8/14 12:26,0,0.0,0.00,0.0,0.00,48841241645050970,None,1000
3,1.0,98.0,اختیارخ شستا-850-1403/08/09,0.0,0,0.0,0,0,0,0.0,...,0.000000e+00,1403/8/9 12:29,0,0.0,0.00,0.0,0.00,18794200601794224,None,1000
4,1.0,1.0,اختیارخ خودرو-4000-1403/03/09,0.0,0,0.0,0,0,0,0.0,...,0.000000e+00,1403/3/9 10:29,0,0.0,0.00,0.0,0.00,414085078149021,None,1000

{'BaseVolume': 1,
 'CP12': 0,
 'ClosingPrice': 1798.0,
 'CompanyTitle': 'اختیارخ اهرم-16000-1403/11/24',
 'GroupStateID': 8,
 'HighAllowedPrice': 500000.0,
 'HighPrice': 1950.0,
 'InstrumentCode': '18154069997422059',
 'IsCautionAgreement': False,
 'IsSepahAgreement': False,
 'LastTradedPrice': 1651.0,
 'LotSize': 1,
 'LowAllowedPrice': 1.0,
 'LowPercent': 100,
 'LowPrice': 1600.0,
 'MarketType': 'MarketType.BuyOption',
 'MaxPercent': 24055,
 'MaxQuantityOrder': 1000,
 'MinQuantityOrder': 1,
 'NSCCode': 'IRO9AHRM2501',
 'RefPrice': 2070.0,
 'Symbol': 'ضهرم1105',
 'SymbolStateId': 1,
 'TickSize': 1.0,
 'TotalNumberOfSharesTraded': 239,
 'TotalNumberOfTrades': 13,
 'TotalTradeValue': 429764000.0,
 'TradeDate': '1403/08/21 - 12:13:45',
 'UA_LastTradedPrice': 16460.0,
 'UA_isin': 'IRT1AHRM0001',
 'YesterdayPrice': 2070.0,
 'contractSize': 1000,
 'contractStartDate': '1403/07/01',
 'cpv': -272.0,
 'cpvp': -13.14,
 'crn': 'ریال',
 'crp': 1,
 'exerciseDate': '1403/11/24',
 'gc': '3A',
 'initial_margin': 3320000.0,
 'iso': True,
 'lpv': -419.0,
 'lpvp': -20.24,
 'mbop': 0,
 'mcaop': 112000,
 'mcop': 112000,
 'mmop': 2250000,
 'openPositionNum': 5712,
 'pv': 0.0,
 'rm': 5118000.0,
 'strikePrice': 16000.0,
 'th': 434306.0,
 'tl': 0.0,
 'vs': -1}

,BestBuyPrice,BestSellPrice,BestSellQuantity,BestBuyQuantity,NoBestBuy,NoBestSell,NSCCode,Place
0,1626.0,1980.0,75,20,1,2,IRO9AHRM2501,1
1,1625.0,1990.0,66,50,1,1,IRO9AHRM2501,2
2,1602.0,2060.0,81,2,1,1,IRO9AHRM2501,3
3,1601.0,2080.0,16,20,1,1,IRO9AHRM2501,4
4,1600.0,2199.0,10,15,1,1,IRO9AHRM2501,5